//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Compras_Edehsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_ListadoDisenoTipo
    {
        public int IdEmpresa { get; set; }
        public int IdTipoListadoDiseno { get; set; }
        public string TipoListadoDiseno { get; set; }
        public string Estado { get; set; }
    }
}
