//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Compras_Edehsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_ListadoDiseno
    {
        public int IdEmpresa { get; set; }
        public decimal IdListadoDiseno { get; set; }
        public string CodObra { get; set; }
        public Nullable<decimal> IdOrdenTaller { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string Estado { get; set; }
        public string ob_descripcion { get; set; }
        public string Usuario { get; set; }
        public string Motivo { get; set; }
        public string lm_Observacion { get; set; }
        public string tipo_listado { get; set; }
        public string Su_Descripcion { get; set; }
        public int IdSucursal { get; set; }
        public string TipoListadoDiseno { get; set; }
    }
}
