//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Inventario_CG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_Inventario_CG : DbContext
    {
        public Entities_Inventario_CG()
            : base("name=Entities_Inventario_CG")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<in_Ing_Egr_Inven_CG> in_Ing_Egr_Inven_CG { get; set; }
        public DbSet<in_categoria_CG> in_categoria_CG { get; set; }
        public DbSet<in_Producto_CG> in_Producto_CG { get; set; }
        public DbSet<vw_in_Producto_x_inv_Producto_CG> vw_in_Producto_x_inv_Producto_CG { get; set; }
    }
}
