//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwACTF_Rpt010
    {
        public int IdEmpresa { get; set; }
        public int IdCambioUbicacion { get; set; }
        public int IdActivoFijo { get; set; }
        public string Af_Nombre { get; set; }
        public int IdActijoFijoTipo { get; set; }
        public string Af_Descripcion { get; set; }
        public int IdSucursal_Actu { get; set; }
        public string SucActual { get; set; }
        public int IdSucursal_Ant { get; set; }
        public string SucAnterior { get; set; }
        public int IdDepartamento_Actu { get; set; }
        public string DepActual { get; set; }
        public int IdDepartamento_Ant { get; set; }
        public string DepAnterior { get; set; }
        public string IdTipoCatalogo_Ubicacion_Actu { get; set; }
        public string UbiActual { get; set; }
        public string IdTipoCatalogo_Ubicacion_Ant { get; set; }
        public string UbiAnterior { get; set; }
        public string MotivoCambio { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public string IdUsuario { get; set; }
        public int Expr1 { get; set; }
    }
}
