//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBAN_Rpt015
    {
        public int mba_IdEmpresa { get; set; }
        public decimal mba_IdCbteCble { get; set; }
        public int mba_IdTipocbte { get; set; }
        public int mcj_Secuencia { get; set; }
        public int IdEmpresa { get; set; }
        public string nom_sucursal { get; set; }
        public decimal IdCbteCble { get; set; }
        public int IdTipocbte { get; set; }
        public string nom_Tipocbte { get; set; }
        public string Beneficiario { get; set; }
        public string IdCobro_tipo { get; set; }
        public System.DateTime Fecha_Cobro { get; set; }
        public double cr_Valor { get; set; }
        public string cm_observacion { get; set; }
    }
}
