//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwINV_Rpt016
    {
        public int IdEmpresa { get; set; }
        public string nom_empresa { get; set; }
        public int IdSucursal { get; set; }
        public string nom_sucursal { get; set; }
        public int IdBodega { get; set; }
        public string nom_bodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public string nom_Movi_inven_tipo { get; set; }
        public decimal IdProducto { get; set; }
        public string nom_Producto { get; set; }
        public string IdSubCentro_Costo { get; set; }
        public string nom_subCentroCosto { get; set; }
        public string IdUnidadMedida { get; set; }
        public string nom_UnidadMedida { get; set; }
        public double dm_cantidad { get; set; }
        public double mv_costo { get; set; }
        public double SubTotal { get; set; }
        public decimal IdNumMovi { get; set; }
        public System.DateTime Fecha { get; set; }
        public string cm_tipo_movi { get; set; }
        public string IdCentroCosto { get; set; }
        public string nom_CentroCosto { get; set; }
    }
}
