//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwINV_Rpt004
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal_oc { get; set; }
        public decimal IdOrdenCompra { get; set; }
        public System.DateTime Fecha_oc { get; set; }
        public string Observacion_oc { get; set; }
        public string Estado_oc { get; set; }
        public decimal IdProveedor { get; set; }
        public string nom_proveedor { get; set; }
        public decimal IdProducto { get; set; }
        public string nom_producto { get; set; }
        public int IdSucursal_inv { get; set; }
        public int IdBodega_inv { get; set; }
        public double Cant_Pedida_oc { get; set; }
        public double Cant_Recibida_inv { get; set; }
        public double Cant_x_Recivir_inv { get; set; }
        public string EstadoPago { get; set; }
    }
}
