//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwINV_Rpt011
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public string CodMoviInven { get; set; }
        public string nom_sucursal { get; set; }
        public string nom_bodega { get; set; }
        public System.DateTime Fecha { get; set; }
        public string cod_Movi_Inven_tipo { get; set; }
        public string nom_Movi_Inven_tipo { get; set; }
        public string NumDocumentoRelacionado { get; set; }
        public string NumFactura { get; set; }
        public string Observacion { get; set; }
        public string mv_tipo_movi { get; set; }
        public double CantiIngreso { get; set; }
        public double CantiEgreso { get; set; }
        public double Costo { get; set; }
        public string Cod_producto { get; set; }
        public string nom_producto { get; set; }
        public decimal IdProducto { get; set; }
    }
}
