//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwROL_Rpt024
    {
        public string CedulaRuc { get; set; }
        public string NombreCompleto { get; set; }
        public decimal IdEmpleado { get; set; }
        public decimal IdPrestamo { get; set; }
        public int IdEmpresa { get; set; }
        public int IdNomina_Tipo { get; set; }
        public string NominaDescripcion { get; set; }
        public string EstadoPrestamo { get; set; }
        public System.DateTime Fecha { get; set; }
        public double MontoSol { get; set; }
        public double TasaInteres { get; set; }
        public double TotalPrestamo { get; set; }
        public int NumCuotas { get; set; }
        public string Observacion { get; set; }
        public int NumCuota { get; set; }
        public double SaldoInicial { get; set; }
        public double Interes { get; set; }
        public double AbonoCapital { get; set; }
        public double TotalCuota { get; set; }
        public double Saldo { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string EstadoPago { get; set; }
        public string ObservacionCuota { get; set; }
        public string RubroDescripcion { get; set; }
        public string CodigoEmpleado { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string ca_descripcion { get; set; }
        public string EstadoCuota { get; set; }
        public double Canceladas { get; set; }
        public double Pendientes { get; set; }
        public Nullable<int> iddivision { get; set; }
    }
}
