//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwROL_Rpt018
    {
        public int IdEmpresa { get; set; }
        public int IdNominaTipo { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNominaTipoLiqui { get; set; }
        public int IdPeriodo { get; set; }
        public string IdRubro { get; set; }
        public int IdDepartamento { get; set; }
        public Nullable<int> pe_anio { get; set; }
        public System.DateTime pe_FechaIni { get; set; }
        public System.DateTime pe_FechaFin { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string ru_descripcion { get; set; }
        public double Valor { get; set; }
        public string de_descripcion { get; set; }
        public string Descripcion { get; set; }
        public int Expr1 { get; set; }
    }
}
