//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwROL_Rpt021
    {
        public int IdEmpresa { get; set; }
        public int IdTipoNomina { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdDepartamento { get; set; }
        public int IdFalta { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public Nullable<int> DiasDescuento { get; set; }
        public Nullable<System.DateTime> FechaDescuentaRol { get; set; }
        public string Descripcion { get; set; }
        public string de_descripcion { get; set; }
    }
}
