CREATE TABLE [Fj_servindustrias].[ro_fectividad_Entrega_servicio_det] (
    [IdEmpresa]        INT          NOT NULL,
    [IdNivelServicio]  NUMERIC (18) NOT NULL,
    [Secuencia]        INT          NOT NULL,
    [IdRuta]           INT          NOT NULL,
    [IdEmpleado]       NUMERIC (18) NOT NULL,
    [Efe_car_bebi]     FLOAT (53)   NOT NULL,
    [Efe_car_bebi_apl] FLOAT (53)   NOT NULL,
    [Efe_vol_bebi]     FLOAT (53)   NOT NULL,
    [Efe_vol_bebi_apl] FLOAT (53)   NOT NULL,
    [Efe_ent_bebi]     FLOAT (53)   NOT NULL,
    [Efe_ent_bebi_apl] FLOAT (53)   NOT NULL,
    [Efe_car_alim]     FLOAT (53)   NOT NULL,
    [Efe_car_alim_ap]  FLOAT (53)   NOT NULL,
    [Efe_vol_alim]     FLOAT (53)   NOT NULL,
    [Efe_vol_alim_apl] FLOAT (53)   NOT NULL,
    [Efe_ent_alim]     FLOAT (53)   NOT NULL,
    [Efe_ent_alim_apl] FLOAT (53)   NOT NULL,
    [Efe_serv]         FLOAT (53)   NOT NULL,
    [Efe_ser_apl]      FLOAT (53)   NOT NULL,
    [Nivel_servicio]   FLOAT (53)   NOT NULL,
    [Valor_volumen]    FLOAT (53)   NOT NULL,
    [Valor_servicio]   FLOAT (53)   NOT NULL,
    [Por_bebida]       FLOAT (53)   NOT NULL,
    [Por_alimento]     FLOAT (53)   NOT NULL,
    CONSTRAINT [PK_ro_fectividad_Entrega_servicio_det] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdNivelServicio] ASC, [Secuencia] ASC),
    CONSTRAINT [FK_ro_fectividad_Entrega_servicio_det_ro_empleado] FOREIGN KEY ([IdEmpresa], [IdEmpleado]) REFERENCES [dbo].[ro_empleado] ([IdEmpresa], [IdEmpleado]),
    CONSTRAINT [FK_ro_fectividad_Entrega_servicio_det_ro_fectividad_Entrega_servicio] FOREIGN KEY ([IdEmpresa], [IdNivelServicio]) REFERENCES [Fj_servindustrias].[ro_fectividad_Entrega_servicio] ([IdEmpresa], [IdNivelServicio])
);

