//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciacionTransgandia_Rpt
    {
        public int IdEmpresa { get; set; }
        public int IdPeriodo { get; set; }
        public int IdActivofijo { get; set; }
        public int Secuencia { get; set; }
        public Nullable<System.DateTime> Fecha_adquisicion { get; set; }
        public string Proveedor { get; set; }
        public string Factura { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Af_nombre { get; set; }
        public Nullable<double> Costo_Unitario_Camion { get; set; }
        public Nullable<double> Costo_unitario_carroceria { get; set; }
        public Nullable<double> ValorSalvamento { get; set; }
        public Nullable<double> TotalDepreciar { get; set; }
        public Nullable<double> DepreciacionMensual { get; set; }
    }
}
