//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities_contabilidad_fj_rpt : DbContext
    {
        public Entities_contabilidad_fj_rpt()
            : base("name=Entities_contabilidad_fj_rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spCONTA_FJ_Rpt001_Result> spCONTA_FJ_Rpt001(Nullable<int> idEmpresa, Nullable<System.DateTime> fecha_ini, Nullable<System.DateTime> fecha_fin, Nullable<int> idPunto_cargo_ini, Nullable<int> idPunto_cargo_fin, Nullable<bool> mostrar_saldo_0, Nullable<int> idNivel)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var fecha_iniParameter = fecha_ini.HasValue ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(System.DateTime));
    
            var idPunto_cargo_iniParameter = idPunto_cargo_ini.HasValue ?
                new ObjectParameter("IdPunto_cargo_ini", idPunto_cargo_ini) :
                new ObjectParameter("IdPunto_cargo_ini", typeof(int));
    
            var idPunto_cargo_finParameter = idPunto_cargo_fin.HasValue ?
                new ObjectParameter("IdPunto_cargo_fin", idPunto_cargo_fin) :
                new ObjectParameter("IdPunto_cargo_fin", typeof(int));
    
            var mostrar_saldo_0Parameter = mostrar_saldo_0.HasValue ?
                new ObjectParameter("Mostrar_saldo_0", mostrar_saldo_0) :
                new ObjectParameter("Mostrar_saldo_0", typeof(bool));
    
            var idNivelParameter = idNivel.HasValue ?
                new ObjectParameter("IdNivel", idNivel) :
                new ObjectParameter("IdNivel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_FJ_Rpt001_Result>("spCONTA_FJ_Rpt001", idEmpresaParameter, fecha_iniParameter, fecha_finParameter, idPunto_cargo_iniParameter, idPunto_cargo_finParameter, mostrar_saldo_0Parameter, idNivelParameter);
        }
    }
}
