//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesFacturacion_FJ_Rpt : DbContext
    {
        public EntitiesFacturacion_FJ_Rpt()
            : base("name=EntitiesFacturacion_FJ_Rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwFAC_FJ_Rpt005> vwFAC_FJ_Rpt005 { get; set; }
        public DbSet<vwFAC_FJ_Rpt014> vwFAC_FJ_Rpt014 { get; set; }
        public DbSet<vwFAC_FJ_Rpt015_ingresos_egresos> vwFAC_FJ_Rpt015_ingresos_egresos { get; set; }
        public DbSet<vwFAC_FJ_Rpt015_logistica> vwFAC_FJ_Rpt015_logistica { get; set; }
        public DbSet<vwFAC_FJ_Rpt015_mano_obra> vwFAC_FJ_Rpt015_mano_obra { get; set; }
        public DbSet<vwFAC_FJ_Rpt015_mano_obra_det> vwFAC_FJ_Rpt015_mano_obra_det { get; set; }
        public DbSet<vwFAC_FJ_Rpt015> vwFAC_FJ_Rpt015 { get; set; }
        public DbSet<vwFAC_FJ_Rpt002> vwFAC_FJ_Rpt002 { get; set; }
        public DbSet<vwFAC_FJ_Rpt003> vwFAC_FJ_Rpt003 { get; set; }
        public DbSet<vwFAC_FJ_Rpt017> vwFAC_FJ_Rpt017 { get; set; }
        public DbSet<vwFAC_FJ_Rpt018> vwFAC_FJ_Rpt018 { get; set; }
        public DbSet<vwFAC_FJ_Rpt004> vwFAC_FJ_Rpt004 { get; set; }
        public DbSet<vwFAC_FJ_Rpt001> vwFAC_FJ_Rpt001 { get; set; }
        public DbSet<vwFAC_FJ_Rpt006> vwFAC_FJ_Rpt006 { get; set; }
        public DbSet<vwFAC_FJ_Rpt008> vwFAC_FJ_Rpt008 { get; set; }
        public DbSet<vwFAC_FJ_Rpt009> vwFAC_FJ_Rpt009 { get; set; }
        public DbSet<vwFAC_FJ_Rpt007> vwFAC_FJ_Rpt007 { get; set; }
        public DbSet<vwFAC_FJ_Rpt016> vwFAC_FJ_Rpt016 { get; set; }
        public DbSet<vwFAC_FJ_Rpt010> vwFAC_FJ_Rpt010 { get; set; }
    
        public virtual ObjectResult<spFAC_FJ_Rpt016_Result> spFAC_FJ_Rpt016(Nullable<int> idEmpresa, Nullable<int> idPeriodo, Nullable<System.DateTime> fechaI, Nullable<System.DateTime> fechaF)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("IdPeriodo", idPeriodo) :
                new ObjectParameter("IdPeriodo", typeof(int));
    
            var fechaIParameter = fechaI.HasValue ?
                new ObjectParameter("FechaI", fechaI) :
                new ObjectParameter("FechaI", typeof(System.DateTime));
    
            var fechaFParameter = fechaF.HasValue ?
                new ObjectParameter("FechaF", fechaF) :
                new ObjectParameter("FechaF", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFAC_FJ_Rpt016_Result>("spFAC_FJ_Rpt016", idEmpresaParameter, idPeriodoParameter, fechaIParameter, fechaFParameter);
        }
    
        public virtual ObjectResult<spFAC_FJ_Rpt017_Result> spFAC_FJ_Rpt017(Nullable<int> idEmpresa, Nullable<decimal> idCliente_ini, Nullable<decimal> idCliente_fin, Nullable<System.DateTime> fecha_ini, Nullable<System.DateTime> fecha_fin, Nullable<bool> no_mostrar_saldo_0)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idCliente_iniParameter = idCliente_ini.HasValue ?
                new ObjectParameter("IdCliente_ini", idCliente_ini) :
                new ObjectParameter("IdCliente_ini", typeof(decimal));
    
            var idCliente_finParameter = idCliente_fin.HasValue ?
                new ObjectParameter("IdCliente_fin", idCliente_fin) :
                new ObjectParameter("IdCliente_fin", typeof(decimal));
    
            var fecha_iniParameter = fecha_ini.HasValue ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(System.DateTime));
    
            var no_mostrar_saldo_0Parameter = no_mostrar_saldo_0.HasValue ?
                new ObjectParameter("No_mostrar_saldo_0", no_mostrar_saldo_0) :
                new ObjectParameter("No_mostrar_saldo_0", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFAC_FJ_Rpt017_Result>("spFAC_FJ_Rpt017", idEmpresaParameter, idCliente_iniParameter, idCliente_finParameter, fecha_iniParameter, fecha_finParameter, no_mostrar_saldo_0Parameter);
        }
    
        public virtual ObjectResult<spFAC_FJ_Rpt007_detallado_Result> spFAC_FJ_Rpt007_detallado(Nullable<int> idEmpresa, Nullable<int> idPeriodo)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("IdPeriodo", idPeriodo) :
                new ObjectParameter("IdPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFAC_FJ_Rpt007_detallado_Result>("spFAC_FJ_Rpt007_detallado", idEmpresaParameter, idPeriodoParameter);
        }
    }
}
