//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    
    public partial class spROLES_Rpt002_Result1
    {
        public int IdEmpresa { get; set; }
        public int IdNominaTipo { get; set; }
        public Nullable<int> pe_anio { get; set; }
        public Nullable<int> pe_mes { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string Nombres { get; set; }
        public string ru_descripcion { get; set; }
        public string ca_descripcion { get; set; }
        public string zo_descripcion { get; set; }
        public string fu_descripcion { get; set; }
        public int ru_orden { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public decimal IdEmpleado { get; set; }
        public string ru_tipo { get; set; }
        public Nullable<int> DiasTraba { get; set; }
        public Nullable<double> Quincena { get; set; }
        public Nullable<double> FindeMes { get; set; }
        public Nullable<double> Variable { get; set; }
        public Nullable<double> FondoReserva { get; set; }
    }
}
