//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFAC_FJ_Rpt010
    {
        public long IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdRegistro { get; set; }
        public int IdActivoFijo { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<decimal> IdCbteVta_hn { get; set; }
        public string vt_NumFactura_hn { get; set; }
        public Nullable<double> Af_ValorUnidad_Actu { get; set; }
        public double unidades_maximas { get; set; }
        public double diferencia_a_facturar { get; set; }
        public int IdPunto_cargo { get; set; }
        public string nom_punto_cargo { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public Nullable<decimal> IdCbteVta_he { get; set; }
        public string vt_NumFactura_he { get; set; }
        public string nom_Centro_costo { get; set; }
        public string nom_Centro_costo_sub_centro_costo { get; set; }
        public string nom_periodo { get; set; }
    }
}
