//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFAC_FJ_Rpt009
    {
        public long IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdCbteVta { get; set; }
        public int Secuencia { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public decimal IdCliente { get; set; }
        public string pe_nombreCompleto { get; set; }
        public int IdVendedor { get; set; }
        public string Ve_Vendedor { get; set; }
        public string pr_descripcion { get; set; }
        public double vt_Subtotal { get; set; }
        public double vt_iva { get; set; }
        public double vt_total { get; set; }
        public int IdPunto_Cargo { get; set; }
        public int IdPunto_cargo_grupo { get; set; }
        public string nom_punto_cargo { get; set; }
        public string vt_NumFactura { get; set; }
    }
}
