//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFAC_FJ_Rpt015_ingresos_egresos
    {
        public long IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string IdCentroCosto { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int eg_secuencia { get; set; }
        public double eg_cantidad { get; set; }
        public double eg_precio_uni { get; set; }
        public double eg_precio_total { get; set; }
        public string pr_descripcion { get; set; }
        public string nom_uni_medida { get; set; }
        public string Tipo { get; set; }
        public string pr_codigo { get; set; }
    }
}
