//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwROLES_Rpt013
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string Empleado { get; set; }
        public string em_codigo { get; set; }
        public string Observacion { get; set; }
        public double Ingresos { get; set; }
        public double Egresos { get; set; }
        public double UltimaRemuneracion { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string IdCausaTerminacion { get; set; }
        public string TipoTerminacion { get; set; }
        public string de_descripcion { get; set; }
        public string ca_descripcion { get; set; }
        public Nullable<double> ValorDesaucio { get; set; }
        public Nullable<int> Antiguedad { get; set; }
        public string EstadoLiquidacion { get; set; }
        public string antiguedad_string { get; set; }
    }
}
