//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwROLES_Rpt015
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public int Id_remplazo { get; set; }
        public string Cedula_empleado_Remplazado { get; set; }
        public string empleado_remplazado { get; set; }
        public string Cedula_remplazo { get; set; }
        public string Remplazo { get; set; }
        public string ca_descripcion { get; set; }
        public Nullable<double> Valor_descuento_empleado { get; set; }
        public Nullable<System.DateTime> Fecha_descuenta_rol { get; set; }
        public double valor_x_dia_remplazo { get; set; }
        public double Total_pagar_remplazo { get; set; }
        public bool Descuenta_rol { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Fecha_Salida { get; set; }
        public System.DateTime Fecha_Entrada { get; set; }
        public string Observacion { get; set; }
        public string MotivoAusencia { get; set; }
        public string Centro_costo { get; set; }
        public string DescripcionProcesoNomina { get; set; }
    }
}
