//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwROLES_Rpt003
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNominaTipo { get; set; }
        public int IdNominaTipoLiqui { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<double> hora_extra25 { get; set; }
        public Nullable<double> hora_extra50 { get; set; }
        public Nullable<double> hora_extra100 { get; set; }
        public Nullable<double> TotalHorasExtras { get; set; }
        public Nullable<double> hora_trabajada { get; set; }
        public Nullable<int> Dias_Efectivos { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_nombre { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombreCompleto { get; set; }
        public int Calculo_Horas_extras_Sobre { get; set; }
    }
}
