CREATE TABLE [dbo].[ro_DiasFaltados_x_Empleado] (
    [IdEmpresa]           INT             NOT NULL,
    [IdEmpleado]          NUMERIC (18)    NOT NULL,
    [IdFalta]             INT             NOT NULL,
    [IdNominaTipo]        INT             NOT NULL,
    [IdNominaTipoLiq]     INT             NOT NULL,
    [CodCatalogo]         VARCHAR (10)    NOT NULL,
    [IdNovedad]           INT             NULL,
    [FechaFaltaDesde]     DATETIME        NOT NULL,
    [FechaFaltaHasta]     DATETIME        NOT NULL,
    [DiasFaltados]        VARCHAR (5)     NOT NULL,
    [DiasDescuento]       INT             NULL,
    [FechaDescuentaRol]   DATETIME        NULL,
    [ValorDescuentaRol]   DECIMAL (18, 2) NULL,
    [Observacion]         VARCHAR (200)   NOT NULL,
    [CatalogoDescripcion] VARCHAR (50)    NOT NULL,
    [estado]              CHAR (1)        NOT NULL,
    [IdUsuario]           VARCHAR (20)    NOT NULL,
    [Fecha_Transac]       DATETIME        NOT NULL,
    [IdUsuarioUltMod]     VARCHAR (20)    NULL,
    [Fecha_UltMod]        DATETIME        NULL,
    [IdUsuarioUltAnu]     VARCHAR (20)    NULL,
    [Fecha_UltAnu]        DATETIME        NULL,
    [nom_pc]              VARCHAR (50)    NULL,
    [ip]                  VARCHAR (25)    NULL,
    [MotiAnula]           VARCHAR (200)   NULL,
    CONSTRAINT [PK_ro_DiasFaltados_x_Empleado] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdEmpleado] ASC, [IdFalta] ASC),
    CONSTRAINT [FK_ro_DiasFaltados_x_Empleado_ro_empleado] FOREIGN KEY ([IdEmpresa], [IdEmpleado]) REFERENCES [dbo].[ro_empleado] ([IdEmpresa], [IdEmpleado])
);

