CREATE TABLE [dbo].[ro_Parametros] (
    [IdEmpresa]                                 INT          NOT NULL,
    [IdTipoCbte_AsientoSueldoXPagar]            INT          NULL,
    [IdTipoCbte_AsientoProvision]               INT          NULL,
    [IdTipo_mov_Ingreso]                        INT          NULL,
    [IdTipo_mov_Egreso]                         INT          NULL,
    [Dias_considerado_ultimo_pago_quincela_Liq] INT          NULL,
    [IdNomina_Tipo_Para_Desc_Automat]           INT          NULL,
    [IdNominatipoLiq_Para_Desc_Automat]         INT          NULL,
    [GeneraraOP_PagoTerceros]                   BIT          NULL,
    [IdTipoOP_PagoTerceros]                     VARCHAR (20) NULL,
    [IdTipoFlujoOP_PagoTerceros]                INT          NULL,
    [IdFormaOP_PagoTerceros]                    VARCHAR (20) NULL,
    [IdBancoOP_PagoTerceros]                    INT          NULL,
    [GeneraOP_PagoPrestamos]                    BIT          NULL,
    [IdTipoOP_PagoPrestamos]                    VARCHAR (20) NULL,
    [IdTipoFlujoOP_PagoPrestamos]               INT          NULL,
    [IdFormaOP_PagoPrestamos]                   VARCHAR (20) NULL,
    [IdBancoOP_PagoPrestamos]                   INT          NULL,
    [GeneraOP_LiquidacionVacaciones]            BIT          NULL,
    [IdTipoOP_LiquidacionVacaciones]            VARCHAR (20) NULL,
    [IdTipoFlujoOP_LiquidacionVacaciones]       INT          NULL,
    [IdFormaOP_LiquidacionVacaciones]           VARCHAR (20) NULL,
    [IdBancoOP_LiquidacionVacaciones]           INT          NULL,
    [DescuentaIESS_LiquidacionVacaciones]       BIT          NULL,
    [cta_contable_IESS_Vacaciones]              VARCHAR (20) NULL,
    [GeneraOP_ActaFiniquito]                    BIT          NULL,
    [IdTipoOP_ActaFiniquito]                    VARCHAR (20) NULL,
    [IdTipoFlujoOP_ActaFiniquito]               INT          NULL,
    [IdFormaPagoOP_ActaFiniquito]               VARCHAR (20) NULL,
    [IdBancoOP_ActaFiniquito]                   INT          NULL,
    CONSTRAINT [PK_ro_Parametros] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC)
);

