CREATE TABLE [dbo].[ro_permiso_x_empleado] (
    [IdEmpresa]                      INT           NOT NULL,
    [IdNomina_Tipo]                  INT           NOT NULL,
    [IdEmpleado]                     NUMERIC (18)  NOT NULL,
    [IdPermiso]                      NUMERIC (18)  NOT NULL,
    [IdEstadoAprob]                  VARCHAR (10)  NOT NULL,
    [IdEmpleado_Apro]                NUMERIC (18)  NULL,
    [IdEmpleado_Soli]                NUMERIC (18)  NULL,
    [IdTipoLicencia]                 VARCHAR (10)  NULL,
    [Id_Forma_descuento_permiso_Cat] VARCHAR (10)  NULL,
    [Dias_tomados]                   INT           NULL,
    [Fecha]                          DATETIME      NOT NULL,
    [MotivoAusencia]                 VARCHAR (250) NOT NULL,
    [TiempoAusencia]                 TIME (7)      NOT NULL,
    [FormaRecuperacion]              VARCHAR (250) NOT NULL,
    [MotivoAproba]                   VARCHAR (250) NULL,
    [Observacion]                    VARCHAR (250) NULL,
    [EsLicencia]                     BIT           NULL,
    [EsPermiso]                      BIT           NULL,
    [FechaSalida]                    DATETIME      NULL,
    [FechaEntrada]                   DATETIME      NULL,
    [HoraSalida]                     VARCHAR (50)  NULL,
    [HoraRegreso]                    VARCHAR (50)  NULL,
    [Estado]                         CHAR (1)      NOT NULL,
    [IdUsuario]                      VARCHAR (20)  NULL,
    [IdUsuario_Anu]                  VARCHAR (20)  NULL,
    [FechaAnulacion]                 DATETIME      NULL,
    [Fecha_Transac]                  DATETIME      NULL,
    [Fecha_UltMod]                   DATETIME      NULL,
    [IdUsuarioUltMod]                VARCHAR (20)  NULL,
    [ip]                             VARCHAR (25)  NULL,
    [nom_pc]                         NCHAR (10)    NULL,
    [MotivoAnulacion]                VARCHAR (250) NULL,
    [IdNovedad]                      NUMERIC (9)   NULL,
    CONSTRAINT [PK_ro_permiso_x_empleado] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdNomina_Tipo] ASC, [IdEmpleado] ASC, [IdPermiso] ASC)
);

