CREATE TABLE [dbo].[ro_rubro_tipo] (
    [IdEmpresa]                      INT            NOT NULL,
    [IdRubro]                        VARCHAR (50)   NOT NULL,
    [rub_codigo]                     VARCHAR (50)   NOT NULL,
    [ru_codRolGen]                   VARCHAR (30)   NOT NULL,
    [ru_descripcion]                 VARCHAR (50)   NOT NULL,
    [NombreCorto]                    VARCHAR (50)   NOT NULL,
    [ru_tipo]                        CHAR (1)       NOT NULL,
    [ru_estado]                      CHAR (1)       NOT NULL,
    [ru_orden]                       INT            NOT NULL,
    [ru_EditablexUser]               CHAR (1)       NOT NULL,
    [IdUsuario]                      VARCHAR (20)   NULL,
    [Fecha_Transac]                  DATETIME       NULL,
    [IdUsuarioUltMod]                VARCHAR (20)   NULL,
    [Fecha_UltMod]                   DATETIME       NULL,
    [IdUsuarioUltAnu]                VARCHAR (20)   NULL,
    [Fecha_UltAnu]                   DATETIME       NULL,
    [nom_pc]                         VARCHAR (50)   NULL,
    [ip]                             VARCHAR (50)   NULL,
    [rub_concep]                     BIT            NULL,
    [rub_tipcal]                     INT            NULL,
    [rub_formul]                     VARCHAR (4000) NULL,
    [rub_valfij]                     MONEY          NULL,
    [rub_legal]                      VARCHAR (10)   NULL,
    [rub_foract]                     VARCHAR (1000) NULL,
    [rub_fornom]                     VARCHAR (1000) NULL,
    [rub_gencon]                     VARCHAR (20)   NULL,
    [rub_antici]                     BIT            NULL,
    [rub_ctacon]                     VARCHAR (20)   NULL,
    [rub_grupo]                      INT            NULL,
    [rub_liquida]                    BIT            NULL,
    [rub_provision]                  BIT            NULL,
    [rub_noafecta]                   BIT            NULL,
    [rub_acumula]                    BIT            NULL,
    [rub_prorrateo]                  BIT            NULL,
    [rub_nocontab]                   BIT            NULL,
    [rub_utilid]                     BIT            NULL,
    [rub_guarda_rol]                 BIT            NULL,
    [rub_aplica_IESS]                BIT            NULL,
    [rub_AplicaEmpleado_Vac]         BIT            NULL,
    [ru_aplica_empleado_Subsidio]    BIT            NULL,
    [rub_Contabiliza_x_empleado]     BIT            NULL,
    [rub_mustra_liquidacion_cliente] BIT            NULL,
    [rub_Acuerdo_Descuento]          VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_ro_rubro_tipo] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdRubro] ASC)
);

