CREATE TABLE [dbo].[ro_Solicitud_Vacaciones_x_empleado] (
    [IdEmpresa]          INT           NOT NULL,
    [IdNomina_Tipo]      INT           NOT NULL,
    [IdSolicitudVaca]    INT           NOT NULL,
    [IdEmpleado]         NUMERIC (9)   NOT NULL,
    [IdEmpleado_aprue]   NUMERIC (9)   NOT NULL,
    [IdEmpleado_remp]    NUMERIC (9)   NULL,
    [IdEstadoAprobacion] VARCHAR (10)  NOT NULL,
    [Fecha]              DATETIME      NOT NULL,
    [AnioServicio]       NCHAR (10)    NOT NULL,
    [Dias_q_Corresponde] NCHAR (10)    NOT NULL,
    [Dias_a_disfrutar]   INT           NOT NULL,
    [Dias_pendiente]     INT           NOT NULL,
    [Anio_Desde]         DATE          NOT NULL,
    [Anio_Hasta]         DATE          NOT NULL,
    [Fecha_Desde]        DATE          NOT NULL,
    [Fecha_Hasta]        DATE          NOT NULL,
    [Fecha_Retorno]      DATE          NOT NULL,
    [Observacion]        VARCHAR (250) NOT NULL,
    [IdUsuario]          VARCHAR (25)  NULL,
    [IdUsuario_Anu]      VARCHAR (25)  NULL,
    [FechaAnulacion]     DATETIME      NULL,
    [Fecha_Transac]      DATETIME      NULL,
    [Fecha_UltMod]       DATETIME      NULL,
    [IdUsuarioUltMod]    VARCHAR (25)  NULL,
    [Estado]             VARCHAR (1)   NULL,
    [MotivoAnulacion]    VARCHAR (250) NULL,
    [ip]                 VARCHAR (250) NULL,
    [nom_pc]             VARCHAR (250) NULL,
    [Gozadas_Pgadas]     BIT           NULL,
    [Canceladas]         BIGINT        NULL,
    CONSTRAINT [PK_ro_Solicitud_Vacaciones_x_empleado] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdNomina_Tipo] ASC, [IdSolicitudVaca] ASC, [IdEmpleado] ASC, [IdEmpleado_aprue] ASC)
);

