CREATE TABLE [CG].[in_Producto_CG] (
    [IdEmpresa]                        INT           NOT NULL,
    [IdProducto]                       NUMERIC (18)  NOT NULL,
    [sw_solicita_autorizacion]         CHAR (1)      NOT NULL,
    [codigo_alterno]                   NVARCHAR (30) NULL,
    [sw_venta_directa]                 CHAR (1)      NULL,
    [codigo_cnmb]                      NVARCHAR (40) NULL,
    [sw_control_fecha_vencimiento]     CHAR (1)      NULL,
    [sw_generico]                      CHAR (1)      NULL,
    [sw_pos]                           CHAR (1)      NULL,
    [med_cod_forma_farmacologica]      NVARCHAR (20) NOT NULL,
    [med_cod_anatofarmacologico]       NVARCHAR (20) NOT NULL,
    [contenido_unidad_venta]           NVARCHAR (60) NULL,
    [med_cod_principio_activo]         NVARCHAR (20) NOT NULL,
    [med_sw_farmacovigilancia]         CHAR (1)      NULL,
    [med_descripcion_alerta]           NVARCHAR (50) NULL,
    [med_sw_alimento_parenteral]       CHAR (1)      NULL,
    [med_sw_alimento_enteral]          CHAR (1)      NULL,
    [med_sw_manejo_luz]                CHAR (1)      NULL,
    [med_unidad_medida_medicamento_id] NVARCHAR (30) NULL,
    [med_dias_previos_vencimiento]     SMALLINT      NOT NULL,
    [IdUsuario]                        NVARCHAR (20) NULL,
    [Fecha_Transac]                    DATETIME      NULL,
    [IdUsuarioUltMod]                  NVARCHAR (20) NULL,
    [Fecha_UltMod]                     DATETIME      NULL,
    [IdUsuarioUltAnu]                  NVARCHAR (20) NULL,
    [Fecha_UltAnu]                     DATETIME      NULL,
    [pr_motivoAnulacion]               NVARCHAR (50) NULL,
    [nom_pc]                           NVARCHAR (50) NULL,
    [ip]                               NVARCHAR (25) NULL,
    [Estado]                           CHAR (1)      NULL,
    CONSTRAINT [PK_in_Producto] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdProducto] ASC)
);

