//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Af_CambioUbicacion_Activo
    {
        public int IdEmpresa { get; set; }
        public int IdCambioUbicacion { get; set; }
        public int IdActivoFijo { get; set; }
        public Nullable<int> IdSucursal_Actu { get; set; }
        public Nullable<int> IdDepartamento_Actu { get; set; }
        public string IdCentroCosto_Actu { get; set; }
        public string IdTipoCatalogo_Ubicacion_Actu { get; set; }
        public Nullable<int> IdSucursal_Ant { get; set; }
        public Nullable<int> IdDepartamento_Ant { get; set; }
        public string IdTipoCatalogo_Ubicacion_Ant { get; set; }
        public string IdCentroCosto_Ant { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public string MotivoCambio { get; set; }
        public string IdUsuario { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public Nullable<double> Af_ValorUnidad_Actu { get; set; }
        public string IdUnidadFact_cat { get; set; }
        public Nullable<decimal> IdEncargado_Ant { get; set; }
        public Nullable<decimal> IdEncargado_Actu { get; set; }
        public string IdCentroCosto_sub_centro_costo_Actu { get; set; }
        public string IdCentroCosto_sub_centro_costo_Ant { get; set; }
    
        public virtual Af_Catalogo Af_Catalogo { get; set; }
        public virtual Af_Catalogo Af_Catalogo1 { get; set; }
        public virtual Af_Departamento Af_Departamento { get; set; }
        public virtual Af_Departamento Af_Departamento1 { get; set; }
        public virtual Af_Activo_fijo Af_Activo_fijo { get; set; }
    }
}
