//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Af_PeriodoDepreciacion
    {
        public Af_PeriodoDepreciacion()
        {
            this.Af_Activo_fijo = new HashSet<Af_Activo_fijo>();
        }
    
        public string IdPeriodoDeprec { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Valor_Ciclo_Anual { get; set; }
    
        public virtual ICollection<Af_Activo_fijo> Af_Activo_fijo { get; set; }
    }
}
