//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Af_ruta
    {
        public int IdEmpresa { get; set; }
        public decimal IdRuta { get; set; }
        public string ru_descripcion { get; set; }
        public double ru_cantidad_km { get; set; }
        public string ru_observacion { get; set; }
        public bool estado { get; set; }
    }
}
