//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class caj_Caja_Movimiento_Tipo_x_CtaCble
    {
        public int IdEmpresa { get; set; }
        public int IdTipoMovi { get; set; }
        public string IdCtaCble { get; set; }
    
        public virtual caj_Caja_Movimiento_Tipo caj_Caja_Movimiento_Tipo { get; set; }
    }
}
