//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class caj_catalogo
    {
        public string IdCatalogo_cj { get; set; }
        public string nom_Catalogo_cj { get; set; }
        public string IdCatalogo_cj_tipo { get; set; }
    }
}
