//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_solicitud_compra_det_pre_aprobacion
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal_SC { get; set; }
        public decimal IdSolicitudCompra { get; set; }
        public int Secuencia_SC { get; set; }
        public string IdEstadoAprobacion { get; set; }
        public string IdUsuarioAprueba { get; set; }
        public Nullable<System.DateTime> FechaHoraAprobacion { get; set; }
        public string do_observacion { get; set; }
    
        public virtual com_catalogo com_catalogo { get; set; }
        public virtual com_solicitud_compra_det com_solicitud_compra_det { get; set; }
    }
}
