//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_GenerOCompra_Det_x_com_ordencompra_local_det_CusCider
    {
        public int goc_IdEmpresa { get; set; }
        public decimal goc_IdTransaccion { get; set; }
        public int goc_IdDetTrans { get; set; }
        public int oc_IdEmpresa { get; set; }
        public int oc_IdSucursal { get; set; }
        public decimal oc_IdOrdenCompra { get; set; }
        public int oc_Secuencia { get; set; }
        public string dummy { get; set; }
    
        public virtual com_GenerOCompra_Det com_GenerOCompra_Det { get; set; }
        public virtual com_ordencompra_local_det com_ordencompra_local_det { get; set; }
    }
}
