//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_conciliacion
    {
        public cp_conciliacion()
        {
            this.cp_conciliacion_det = new HashSet<cp_conciliacion_det>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdConciliacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public string MotivoAnu { get; set; }
        public string nom_pc { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string ip { get; set; }
        public Nullable<decimal> IdCancelacion { get; set; }
        public string Tipo_detalle { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdEmpresa_cbtecble { get; set; }
        public Nullable<int> IdTipoCbte_cbtecble { get; set; }
        public Nullable<decimal> IdCbteCble_cbtecble { get; set; }
    
        public virtual ICollection<cp_conciliacion_det> cp_conciliacion_det { get; set; }
    }
}
