//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_proveedor_Autorizacion
    {
        public int IdEmpresa { get; set; }
        public decimal IdProveedor { get; set; }
        public decimal IdAutorizacion { get; set; }
        public string Serie1 { get; set; }
        public string Serie2 { get; set; }
        public string nAutorizacion { get; set; }
        public System.DateTime Valido_Hasta { get; set; }
        public string factura_inicial { get; set; }
        public string factura_final { get; set; }
        public string NumAutorizacionImprenta { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual cp_proveedor cp_proveedor { get; set; }
    }
}
