//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_proveedor_contactos
    {
        public int IdEmpresa_prov { get; set; }
        public decimal IdProveedor { get; set; }
        public int IdEmpresa_cont { get; set; }
        public decimal IdContacto { get; set; }
        public string observacion { get; set; }
    
        public virtual cp_proveedor cp_proveedor { get; set; }
    }
}
