//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_distribucion_gastos_x_periodo
    {
        public ct_distribucion_gastos_x_periodo()
        {
            this.ct_distribucion_gastos_x_periodo_det = new HashSet<ct_distribucion_gastos_x_periodo_det>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdDistribucion { get; set; }
        public int IdPeriodo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<ct_distribucion_gastos_x_periodo_det> ct_distribucion_gastos_x_periodo_det { get; set; }
    }
}
