//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_GrupoEmpresarial_grupocble
    {
        public ct_GrupoEmpresarial_grupocble()
        {
            this.ct_GrupoEmpresarial_plancta = new HashSet<ct_GrupoEmpresarial_plancta>();
        }
    
        public string IdGrupoCble_gr { get; set; }
        public string gc_GrupoCble_gr { get; set; }
        public int gc_Orden { get; set; }
        public string gc_estado_financiero { get; set; }
        public int gc_signo_operacion { get; set; }
    
        public virtual ICollection<ct_GrupoEmpresarial_plancta> ct_GrupoEmpresarial_plancta { get; set; }
    }
}
