//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_GrupoEmpresarial
    {
        public ct_GrupoEmpresarial()
        {
            this.ct_GrupoEmpresarial_plancta_x_ct_plancta = new HashSet<ct_GrupoEmpresarial_plancta_x_ct_plancta>();
        }
    
        public string IdGrupoEmpresarial { get; set; }
        public string GrupoEmpresarial { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<ct_GrupoEmpresarial_plancta_x_ct_plancta> ct_GrupoEmpresarial_plancta_x_ct_plancta { get; set; }
    }
}
