//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_rpt_SaldoxCta
    {
        public int IdEmpresa { get; set; }
        public string IdCtaCble { get; set; }
        public double sa_SaldoInicial { get; set; }
        public double sa_Debitos { get; set; }
        public double sa_Creditos { get; set; }
        public double sa_SaldoFinal { get; set; }
    }
}
