//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_saldoxCuentas
    {
        public int IdEmpresa { get; set; }
        public int IdAnioF { get; set; }
        public int IdPeriodo { get; set; }
        public string IdCtaCble { get; set; }
        public byte IdNivel { get; set; }
        public double sc_saldo_anterior { get; set; }
        public double sc_debito_mes { get; set; }
        public double sc_credito_mes { get; set; }
        public double sc_saldo_mes { get; set; }
        public double sc_saldo_acum { get; set; }
    
        public virtual ct_periodo ct_periodo { get; set; }
        public virtual ct_anio_fiscal ct_anio_fiscal { get; set; }
        public virtual ct_plancta ct_plancta { get; set; }
    }
}
