//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_cobro_x_tarjeta
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCobro { get; set; }
        public string IdCobro_tipo { get; set; }
        public decimal IdCobro_Aplicado { get; set; }
        public string IdCobro_tipo_Aplicado { get; set; }
        public decimal IdCbte_vta_aplicado { get; set; }
    
        public virtual cxc_cobro cxc_cobro { get; set; }
    }
}
