//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_compensacion_x_ct_centro_costo
    {
        public int IdEmpresa { get; set; }
        public int IdCompensacion { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public string observacion { get; set; }
        public double valor_a_financiar { get; set; }
        public double num_cuotas_meses_x_centro_costo { get; set; }
        public double num_cuotas_meses_x_banco { get; set; }
        public double tasa_interes_anual_x_centro_costo { get; set; }
        public double tasa_interes_anual_x_banco { get; set; }
        public bool estado { get; set; }
    }
}
