//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_descuento
    {
        public fa_descuento()
        {
            this.fa_factura_det_x_fa_descuento = new HashSet<fa_factura_det_x_fa_descuento>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdDescuento { get; set; }
        public string de_nombre { get; set; }
        public string de_IdCtaCble { get; set; }
        public double de_porcentaje { get; set; }
        public string de_observacion { get; set; }
        public bool Estado { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> FechaUltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotiAnula { get; set; }
        public string ip { get; set; }
        public string nom_pc { get; set; }
    
        public virtual ICollection<fa_factura_det_x_fa_descuento> fa_factura_det_x_fa_descuento { get; set; }
    }
}
