//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_guia_remision_x_prd_Despacho
    {
        public int IdEmpresa_guia { get; set; }
        public int IdSucursal_guia { get; set; }
        public int IdBodega_guia { get; set; }
        public decimal IdGuiaRemision_guia { get; set; }
        public int IdEmpresa_des { get; set; }
        public int IdSucursal_des { get; set; }
        public string IdCentroCosto_des { get; set; }
        public decimal IdDespacho_des { get; set; }
    }
}
