//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_liquidacion_x_punto_cargo_det_logistica
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string IdCentroCosto { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int lo_secuencia { get; set; }
        public decimal IdRuta { get; set; }
        public double lo_cantidad { get; set; }
        public double lo_kilometros { get; set; }
        public double lo_precio_uni_kilometro { get; set; }
        public double lo_por_ganancia { get; set; }
        public double lo_valor_ganancia { get; set; }
        public double lo_precio_total { get; set; }
    
        public virtual fa_liquidacion_x_punto_cargo fa_liquidacion_x_punto_cargo { get; set; }
    }
}
