//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_liquidacion_x_punto_cargo_x_fa_factura
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string IdCentroCosto { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int IdEmpresa_vta { get; set; }
        public int IdSucursal_vta { get; set; }
        public int IdBodega_vta { get; set; }
        public decimal IdCbteVta { get; set; }
        public double vta_subtotal { get; set; }
        public double vta_iva { get; set; }
        public double vta_total { get; set; }
    
        public virtual fa_liquidacion_x_punto_cargo fa_liquidacion_x_punto_cargo { get; set; }
    }
}
