//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_orden_Desp_det_x_fa_pedido_det
    {
        public int od_IdEmpresa { get; set; }
        public int od_IdSucursal { get; set; }
        public int od_IdBodega { get; set; }
        public decimal od_IdOrdenDespacho { get; set; }
        public int od_Secuencia { get; set; }
        public decimal od_IdProducto { get; set; }
        public double od_cantidad { get; set; }
        public int pe_IdEmpresa { get; set; }
        public int pe_IdSucursal { get; set; }
        public int pe_IdBodega { get; set; }
        public decimal pe_IdPedido { get; set; }
        public int pe_Secuencia { get; set; }
        public decimal pe_IdProducto { get; set; }
    
        public virtual fa_orden_Desp_det fa_orden_Desp_det { get; set; }
        public virtual fa_pedido_det fa_pedido_det { get; set; }
    }
}
