//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_pre_facturacion_activos
    {
        public int IdEmpresa { get; set; }
        public decimal IdPreFacturacion { get; set; }
        public int Secuencia { get; set; }
        public int IdActivoFijo { get; set; }
        public double por_ganancia { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public int IdPeriodo_ini { get; set; }
        public int IdPeriodo_fin { get; set; }
        public int cant_act_x_scc { get; set; }
        public decimal IdGrupo { get; set; }
        public Nullable<double> valor_depr_x_scc { get; set; }
        public Nullable<double> valor_movilizacion { get; set; }
    
        public virtual fa_grupo_x_sub_centro_costo fa_grupo_x_sub_centro_costo { get; set; }
        public virtual fa_pre_facturacion fa_pre_facturacion { get; set; }
    }
}
