//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_pedido_estadoAprobacion
    {
        public fa_pedido_estadoAprobacion()
        {
            this.fa_pedido = new HashSet<fa_pedido>();
            this.fa_parametro = new HashSet<fa_parametro>();
        }
    
        public string IdEstadoAprobacion { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public int posicion { get; set; }
    
        public virtual ICollection<fa_pedido> fa_pedido { get; set; }
        public virtual ICollection<fa_parametro> fa_parametro { get; set; }
    }
}
