//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_pre_facturacion_det_Cobro_x_Depreciacion
    {
        public int IdEmpresa { get; set; }
        public decimal IdPreFacturacion { get; set; }
        public int secuencia { get; set; }
        public string IdCentro_Costo { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public int IdPunto_cargo { get; set; }
        public int IdEmpresa_dep { get; set; }
        public decimal IdDepreciacion_dep { get; set; }
        public Nullable<decimal> IdTarifario { get; set; }
        public double Porc_ganancia { get; set; }
        public bool Facturar { get; set; }
        public int secuencia_dep { get; set; }
        public int IdActivoFijo { get; set; }
        public string concepto { get; set; }
        public double Total_depreciado_x_cobrar { get; set; }
        public Nullable<double> Costo_unitario { get; set; }
        public Nullable<double> Valor_salvamento { get; set; }
    }
}
