//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_pre_facturacion_det_gasto_Interes_Banc
    {
        public int IdEmpresa { get; set; }
        public decimal IdPreFacturacion { get; set; }
        public int secuencia { get; set; }
        public decimal IdPrestamo { get; set; }
        public int IdSecuencia_Prestamo { get; set; }
        public decimal IdCliente { get; set; }
        public double Valor { get; set; }
        public string Observacion { get; set; }
    }
}
