//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_pre_facturacion
    {
        public fa_pre_facturacion()
        {
            this.fa_pre_facturacion_det = new HashSet<fa_pre_facturacion_det>();
            this.fa_pre_facturacion_mano_obra_servindustria = new HashSet<fa_pre_facturacion_mano_obra_servindustria>();
            this.fa_pre_facturacion_det_otros = new HashSet<fa_pre_facturacion_det_otros>();
            this.fa_pre_facturacion_activos = new HashSet<fa_pre_facturacion_activos>();
            this.fa_pre_facturacion_det_ing_egr_inven = new HashSet<fa_pre_facturacion_det_ing_egr_inven>();
            this.fa_pre_facturacion_det_Fact_x_Gastos = new HashSet<fa_pre_facturacion_det_Fact_x_Gastos>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdPreFacturacion { get; set; }
        public int IdPeriodo { get; set; }
        public string Observacion { get; set; }
        public bool estado_cierre { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
        public string IdCentroCosto { get; set; }
        public int TotalEquipos { get; set; }
        public double ValorFacturar { get; set; }
    
        public virtual ICollection<fa_pre_facturacion_det> fa_pre_facturacion_det { get; set; }
        public virtual ICollection<fa_pre_facturacion_mano_obra_servindustria> fa_pre_facturacion_mano_obra_servindustria { get; set; }
        public virtual ICollection<fa_pre_facturacion_det_otros> fa_pre_facturacion_det_otros { get; set; }
        public virtual ICollection<fa_pre_facturacion_activos> fa_pre_facturacion_activos { get; set; }
        public virtual ICollection<fa_pre_facturacion_det_ing_egr_inven> fa_pre_facturacion_det_ing_egr_inven { get; set; }
        public virtual ICollection<fa_pre_facturacion_det_Fact_x_Gastos> fa_pre_facturacion_det_Fact_x_Gastos { get; set; }
    }
}
