//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_tarifario_horometro_det
    {
        public int IdEmpresa { get; set; }
        public int IdTarifario { get; set; }
        public int Secuencia { get; set; }
        public int IdActivoFijo { get; set; }
        public double valor_unidad { get; set; }
        public double unidades_minimas { get; set; }
        public double total_valor_x_unidades_minimas { get; set; }
    
        public virtual fa_tarifario_horometro fa_tarifario_horometro { get; set; }
    }
}
