//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Guia_x_traspaso_bodega_det_sin_oc
    {
        public int IdEmpresa { get; set; }
        public decimal IdGuia { get; set; }
        public int secuencia { get; set; }
        public string Num_Fact { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string nom_proveedor { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public string nom_producto { get; set; }
        public double Cantidad_enviar { get; set; }
        public string observacion { get; set; }
    
        public virtual in_Guia_x_traspaso_bodega in_Guia_x_traspaso_bodega { get; set; }
        public virtual in_Producto in_Producto { get; set; }
    }
}
