//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_movi_inve_x_in_ordencompra_local
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public int IdEmpresaOC { get; set; }
        public int IdSucursalOC { get; set; }
        public decimal IdOrdenCompra { get; set; }
        public string observacion { get; set; }
    
        public virtual in_movi_inve in_movi_inve { get; set; }
    }
}
