//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_movi_inven_x_in_movi_inven_CusCidersus
    {
        public int IdEmpresa1 { get; set; }
        public int IdSucursal1 { get; set; }
        public int IdBodega1 { get; set; }
        public int IdMovi_inven_tipo1 { get; set; }
        public decimal IdNumMovi1 { get; set; }
        public int IdEmpresa2 { get; set; }
        public int IdSucursal2 { get; set; }
        public int IdBodega2 { get; set; }
        public int IdMovi_inven_tipo2 { get; set; }
        public decimal IdNumMovi2 { get; set; }
        public string dummy { get; set; }
    }
}
