//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_transferencia_x_in_Guia_x_traspaso_bodega
    {
        public int IdEmpresa { get; set; }
        public int IdSucursalOrgen { get; set; }
        public int IdBodegaOrigen { get; set; }
        public decimal IdTransferencia { get; set; }
        public int IdEmpresa_Guia { get; set; }
        public decimal IdGuia { get; set; }
        public string Observacion { get; set; }
    
        public virtual in_transferencia in_transferencia { get; set; }
        public virtual in_Guia_x_traspaso_bodega in_Guia_x_traspaso_bodega { get; set; }
    }
}
