//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_alerta : DbContext
    {
        public Entities_alerta()
            : base("name=Entities_alerta")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_sis_alerta> tb_sis_alerta { get; set; }
        public DbSet<tb_sis_alerta_auditoria> tb_sis_alerta_auditoria { get; set; }
        public DbSet<tb_sis_alerta_x_usuario_x_empresa> tb_sis_alerta_x_usuario_x_empresa { get; set; }
        public DbSet<tb_sis_alerta_x_usuario_x_empresa_x_eventos> tb_sis_alerta_x_usuario_x_empresa_x_eventos { get; set; }
        public DbSet<vwtb_sis_alerta_x_usuario_x_empresa_x_eventos> vwtb_sis_alerta_x_usuario_x_empresa_x_eventos { get; set; }
    }
}
