//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prd_Conversion_det_CusCidersus
    {
        public int IdEmpresa { get; set; }
        public decimal IdConversion { get; set; }
        public int Secuencial { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public string CodBarra { get; set; }
        public string TipoPro { get; set; }
        public string Observacion { get; set; }
    }
}
