//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prd_ControlInventarioProd
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string CodObra { get; set; }
        public int IdRegistro { get; set; }
        public int IdEtapa { get; set; }
        public int IdOrdenTrabajo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string TipoMov { get; set; }
        public double Kilos { get; set; }
        public double Unidades { get; set; }
        public string Observacion { get; set; }
    }
}
