//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prd_ControlProduccion_Obrero_x_in_movi_inve
    {
        public int cp_IdEmpresa { get; set; }
        public int cp_IdSucursal { get; set; }
        public decimal cp_IdControlProduccionObrero { get; set; }
        public int mv_IdEmpresa { get; set; }
        public int mv_IdSucursal { get; set; }
        public int mv_IdBodega { get; set; }
        public int mv_IdMovi_inven_tipo { get; set; }
        public decimal mv_IdNumMovi { get; set; }
    }
}
