//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_CompraChatarra_CusTalme_x__in_movi_inven
    {
        public int IdEmpresa { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int mv_IdEmpresa { get; set; }
        public int mv_IdSucursal { get; set; }
        public int mv_IdBodega { get; set; }
        public int mv_IdMovi_inven_tipo { get; set; }
        public decimal mv_IdNumMovi { get; set; }
        public string None { get; set; }
    }
}
