//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_ParametrosAceria
    {
        public int IdEmpresa { get; set; }
        public Nullable<int> IdSucursalEgresoMovi { get; set; }
        public Nullable<int> IdBodegaEgresoMovi { get; set; }
        public Nullable<int> IdMoviInvenTipoEgreso { get; set; }
        public Nullable<int> IdSucursalIngresoMovi { get; set; }
        public Nullable<int> IdBodegaIngresoMovi { get; set; }
        public Nullable<int> IdMoviInvenTipoIngreso { get; set; }
    }
}
