//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_Costeo_Rubros_x_Tipo_costeo_Datos_cusTalme
    {
        public int IdEmpresa { get; set; }
        public string IdTipo_Costeo { get; set; }
        public string IdRubroCosteo { get; set; }
        public int Anio { get; set; }
        public int mes { get; set; }
        public double ValorParcial_Mes { get; set; }
        public double Valorkilos_Mes { get; set; }
        public double ValorDolares_Mes { get; set; }
        public double ValorParcial_Acu { get; set; }
        public double Valorkilos_Acu { get; set; }
        public double ValorDolares_Acu { get; set; }
        public double CostoUnitario { get; set; }
    }
}
