//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_Costeo_Rubros_x_tipo_costeo_Parametros_cusTalme
    {
        public int IdEmpresa { get; set; }
        public string IdTipo_Costeo { get; set; }
        public string IdRubroCosteo { get; set; }
        public string IdCtaCble { get; set; }
        public string IdCentroCosto { get; set; }
    }
}
