//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_Costeo_ParametrosGenerales
    {
        public int IdEmpresa { get; set; }
        public int pa_IdMovi_inven_tipo_SaldoInicial { get; set; }
    }
}
