//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_Clave_Autorizacion
    {
        public int IdEmpresa { get; set; }
        public decimal IdGeneracion { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> IdModeloProduccion { get; set; }
        public string Clave { get; set; }
        public string IdUsuarioUsoDeClave { get; set; }
        public Nullable<System.DateTime> FechaUsoDeClave { get; set; }
        public string IdUsuarioGeneracion { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<decimal> IdTransaccion { get; set; }
        public string Activo { get; set; }
    }
}
