//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_Asignacion_Implemento_x_Empleado_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdAsignacion_Impl { get; set; }
        public decimal IdProducto { get; set; }
        public int secuencia { get; set; }
        public string Detalle { get; set; }
        public int Vida_Util { get; set; }
        public double Cantidad { get; set; }
        public System.DateTime Fecha_Caducidad { get; set; }
        public string Estado_implemnto { get; set; }
    }
}
