//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_descuento_no_planificados_Det
    {
        public int IdEmpresa { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_Tipo_Liq { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdDescuento { get; set; }
        public string IdRubro { get; set; }
        public int Secuencia { get; set; }
        public string Observacion { get; set; }
        public double Valor { get; set; }
        public System.DateTime Fecha_Descuento { get; set; }
    }
}
