//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_empleado_x_cargo_fuerza_grupo
    {
        public int IdEmpresa { get; set; }
        public int IdNomina { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdPeriodo { get; set; }
        public int IdFuerza { get; set; }
        public int IdGrupo { get; set; }
        public int IdCargo { get; set; }
        public string Observacion { get; set; }
    
        public virtual ro_Grupo_empleado ro_Grupo_empleado { get; set; }
        public virtual ro_fuerza ro_fuerza { get; set; }
    }
}
