//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_Historico_Liquidacion_Vacaciones_Det_DescNovedad
    {
        public int IdEmpresa { get; set; }
        public int IdNomina_tipo { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdSolicitud_Vacaciones { get; set; }
        public decimal IdNovedad { get; set; }
        public int IdNomina_Tipo_Liq { get; set; }
        public string IdRubro { get; set; }
        public int Secuencia { get; set; }
        public double Valor { get; set; }
    
        public virtual ro_empleado_novedad_det ro_empleado_novedad_det { get; set; }
        public virtual ro_Historico_Liquidacion_Vacaciones ro_Historico_Liquidacion_Vacaciones { get; set; }
    }
}
