//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_IdRol
    {
        public string IdRol { get; set; }
        public int iAnio { get; set; }
        public int iMes { get; set; }
        public Nullable<int> iQuincena { get; set; }
        public Nullable<int> iSemana { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Cerrado { get; set; }
    }
}
