//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_planificacion_x_jornada_desfasada_empleado
    {
        public int IdEmpresa { get; set; }
        public int IdPlanificacion { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdPeriodo { get; set; }
        public int IdMes { get; set; }
        public int IdAnio { get; set; }
        public decimal IdTurno { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
    
        public virtual ro_planificacion_x_jornada_desfasada ro_planificacion_x_jornada_desfasada { get; set; }
    }
}
