//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_presupuesto_x_fuerza_x_cargo
    {
        public int IdEmpresa { get; set; }
        public int IdNomina { get; set; }
        public int IdFuerza { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public int IdCargo { get; set; }
        public decimal CantidadEmpleados { get; set; }
        public double Presupuesto { get; set; }
        public string Observacion { get; set; }
        public int Dias_SyD_y_Feriado { get; set; }
        public int diasEfectivos { get; set; }
        public Nullable<double> BaseVariable { get; set; }
    
        public virtual ro_fuerza ro_fuerza { get; set; }
    }
}
