//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_Parametro_calculo_Horas_Extras
    {
        public int IdEmpresa { get; set; }
        public bool Se_calcula_horas_Extras_al100 { get; set; }
        public bool Se_calcula_horas_Extras_al50 { get; set; }
        public bool Se_calcula_horas_Extras_al25 { get; set; }
        public int Corte_Horas_extras { get; set; }
        public bool Se_Crea_reverso_h_extras_si_Emp_tiene_remplazo { get; set; }
        public string IdRubro_rev_Horas { get; set; }
        public string IdRubro_Rebaja_Desahucio { get; set; }
        public Nullable<int> MinutosLunch { get; set; }
        public Nullable<bool> considera_fecha_corte_dias_efectivo { get; set; }
        public Nullable<bool> solo_graba_dias_efectivos { get; set; }
    }
}
