//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_TablaSectorial
    {
        public ro_TablaSectorial()
        {
            this.ro_empleado = new HashSet<ro_empleado>();
        }
    
        public int IdCodSectorial { get; set; }
        public string CodigoIESS { get; set; }
        public string Actividad { get; set; }
        public string EstructuraOcupacional { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> FechaHoraAnul { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual ICollection<ro_empleado> ro_empleado { get; set; }
    }
}
