//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_Menu_Grupo_x_seg_Menu_Item
    {
        public string Codigo_Item { get; set; }
        public string Codigo_Grupo { get; set; }
        public string observacion { get; set; }
    
        public virtual seg_Menu_Grupo seg_Menu_Grupo { get; set; }
        public virtual seg_Menu_Item seg_Menu_Item { get; set; }
    }
}
