//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_Menu_Item_Tipo
    {
        public seg_Menu_Item_Tipo()
        {
            this.seg_Menu_Item = new HashSet<seg_Menu_Item>();
        }
    
        public string IdTipo_Item { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<seg_Menu_Item> seg_Menu_Item { get; set; }
    }
}
