//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_alerta
    {
        public string CodAlerta { get; set; }
        public string Nombre { get; set; }
        public string CodModulo { get; set; }
        public string VistaRpt { get; set; }
        public string Formulario { get; set; }
        public string Class_NomReporte { get; set; }
        public string nom_Asembly { get; set; }
        public string Class_Info { get; set; }
        public string Class_Bus { get; set; }
        public string Class_Data { get; set; }
        public bool Estado { get; set; }
        public string observacion { get; set; }
    }
}
