//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_iconos
    {
        public string IdIcono { get; set; }
        public byte[] Icono { get; set; }
        public string descripcion { get; set; }
        public string Extencion { get; set; }
        public string FullName { get; set; }
        public decimal Length { get; set; }
        public string DirectoryName { get; set; }
    }
}
