//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_alerta_x_usuario_x_empresa
    {
        public tb_sis_alerta_x_usuario_x_empresa()
        {
            this.tb_sis_alerta_x_usuario_x_empresa_x_eventos = new HashSet<tb_sis_alerta_x_usuario_x_empresa_x_eventos>();
        }
    
        public int IdEmpresa { get; set; }
        public string IdUsuario { get; set; }
        public string CodAlerta { get; set; }
        public Nullable<int> IdSucursal { get; set; }
    
        public virtual ICollection<tb_sis_alerta_x_usuario_x_empresa_x_eventos> tb_sis_alerta_x_usuario_x_empresa_x_eventos { get; set; }
    }
}
