//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tarjeta
    {
        public tb_tarjeta()
        {
            this.tb_tarjeta_parametro = new HashSet<tb_tarjeta_parametro>();
        }
    
        public int IdTarjeta { get; set; }
        public string tr_Descripcion { get; set; }
        public string Estado { get; set; }
        public int IdBanco { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transaccion { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual ICollection<tb_tarjeta_parametro> tb_tarjeta_parametro { get; set; }
    }
}
