//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlh_evaluacion_opciones_preguntas_respuesta_det
    {
        public int IdEmpresa { get; set; }
        public int IdCalendario { get; set; }
        public int IdPregunta { get; set; }
        public decimal IdEmpleado { get; set; }
        public int secuencia { get; set; }
        public string Observacion { get; set; }
        public bool Respueta { get; set; }
    
        public virtual tlh_evaluacion_opciones_preguntas_det tlh_evaluacion_opciones_preguntas_det { get; set; }
        public virtual tlh_evaluacion_opciones_preguntas_respuesta tlh_evaluacion_opciones_preguntas_respuesta { get; set; }
    }
}
