//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlh_evaluacion_opciones_preguntas
    {
        public tlh_evaluacion_opciones_preguntas()
        {
            this.tlh_evaluacion_opciones_preguntas_det = new HashSet<tlh_evaluacion_opciones_preguntas_det>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdPregunta { get; set; }
        public int IdOpciones { get; set; }
        public int Numero_opciones { get; set; }
        public string Descripcion { get; set; }
        public bool estado { get; set; }
    
        public virtual tlh_evaluacion_opciones tlh_evaluacion_opciones { get; set; }
        public virtual ICollection<tlh_evaluacion_opciones_preguntas_det> tlh_evaluacion_opciones_preguntas_det { get; set; }
    }
}
