//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Persona
    {
        public decimal IdPersona { get; set; }
        public string Nombre_Completo { get; set; }
        public string Razon_Social { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Cedula_Ruc { get; set; }
        public string Direccion { get; set; }
        public string Tel_Casa { get; set; }
        public string Tel_Oficina { get; set; }
        public string Tel_Internacional { get; set; }
        public string Tel_Contacto { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public string Fax { get; set; }
        public string Casilla { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
    }
}
