//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WSProduccionCidersus_Trazabilidad_IngresoEtapas
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdMovimiento { get; set; }
        public string CodigoBarra { get; set; }
        public string NombreEtapa { get; set; }
        public string DescripcionPieza { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaTransaccion { get; set; }
    }
}
