//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_ordenesCompras_Aprobadas
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string g_ocObservacion { get; set; }
        public string Estado { get; set; }
        public string pr_nombre { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> IdDetalle { get; set; }
        public Nullable<decimal> IdListadoMateriales { get; set; }
        public System.DateTime FechaRequer { get; set; }
        public string IdEstadoAprob { get; set; }
        public double Kg { get; set; }
        public double Cantidad { get; set; }
        public decimal IdProducto { get; set; }
        public string Motivo { get; set; }
        public decimal IdOrdenTaller { get; set; }
        public string CodObra { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string pr_descripcion { get; set; }
        public decimal IdTransaccion { get; set; }
        public int IdDetTrans { get; set; }
    }
}
