//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_proveedor_combo
    {
        public int IdEmpresa { get; set; }
        public decimal IdProveedor { get; set; }
        public string pe_nombrecompleto { get; set; }
        public string pe_cedularuc { get; set; }
    }
}
