//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_nota_DebCre_total_saldo
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble_Nota { get; set; }
        public int IdTipoCbte_Nota { get; set; }
        public string DebCre { get; set; }
        public decimal IdProveedor { get; set; }
        public System.DateTime cn_fecha { get; set; }
        public string serie { get; set; }
        public string cn_Nota { get; set; }
        public System.DateTime Fecha_Transac { get; set; }
        public Nullable<System.DateTime> Fecha_contable { get; set; }
        public System.DateTime cn_Fecha_vcto { get; set; }
        public string cn_observacion { get; set; }
        public decimal cn_total { get; set; }
        public decimal valorpagar { get; set; }
        public double TotalPagado { get; set; }
        public Nullable<double> SaldoOG { get; set; }
    }
}
