//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_Anticipos_para_Conciliar
    {
        public Nullable<int> IdEmpresa_cxp { get; set; }
        public Nullable<decimal> IdCbteCble_cxp { get; set; }
        public Nullable<int> IdTipoCbte_cxp { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public string referencia { get; set; }
        public string tc_TipoCbte { get; set; }
        public double Valor_cbte { get; set; }
        public double Valor_cancelado { get; set; }
        public double valor_saldo_cbte { get; set; }
        public string tipo { get; set; }
        public int IdEmpresaOP { get; set; }
        public decimal IdOrdenPagoOP { get; set; }
        public int SecuenciaOP { get; set; }
        public string IdCtaCble { get; set; }
        public string IdCtaCble_Anticipo { get; set; }
        public string Beneficiario { get; set; }
        public decimal IdProveedor { get; set; }
        public decimal IdPersona { get; set; }
    }
}
