//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_con_saldo_cxp
    {
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<decimal> IdCbteCble { get; set; }
        public Nullable<int> IdTipocbte { get; set; }
        public System.DateTime cb_Fecha { get; set; }
        public string cb_Observacion { get; set; }
        public string referencia { get; set; }
        public string tc_TipoCbte { get; set; }
        public Nullable<double> Valor_cbte { get; set; }
        public double Valor_cancelado_cbte { get; set; }
        public Nullable<double> valor_Saldo_cbte { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdEmpresaOP { get; set; }
        public Nullable<decimal> IdOrdenPagoOP { get; set; }
        public Nullable<int> SecuenciaOP { get; set; }
        public string IdCtaCble { get; set; }
        public string IdCtaCble_Anticipo { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<decimal> IdBeneficiario { get; set; }
    }
}
