//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_punto_cargo_x_Af_Activo_fijo
    {
        public int IdEmpresa { get; set; }
        public int IdPunto_cargo { get; set; }
        public string codPunto_cargo { get; set; }
        public string nom_punto_cargo { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdPunto_cargo_grupo { get; set; }
        public string IdCentroCosto_Scc { get; set; }
        public string IdCentroCosto_sub_centro_costo_Scc { get; set; }
        public string nom_centro { get; set; }
        public string nom_subcentro { get; set; }
        public Nullable<int> IdActivoFijo { get; set; }
    }
}
