//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_cobro_x_anticipo_total_respaldado
    {
        public int IdEmpresa { get; set; }
        public decimal IdAnticipo { get; set; }
        public int Secuencia_ant { get; set; }
        public int IdEmpresa_cbr { get; set; }
        public int IdSucursal_cbr { get; set; }
        public decimal IdCobro_cbr { get; set; }
        public Nullable<double> Total_Pagado { get; set; }
    }
}
