//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_cancelacion_Intercompany_x_cxc_cobro_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdCancelacion { get; set; }
        public int Secuencia { get; set; }
        public decimal IdCobro { get; set; }
        public System.DateTime cr_fecha { get; set; }
        public System.DateTime cr_fechaDocu { get; set; }
        public System.DateTime cr_fechaCobro { get; set; }
        public string cr_observacion { get; set; }
        public string cr_Banco { get; set; }
        public string cr_cuenta { get; set; }
        public string cr_NumDocumento { get; set; }
        public string cr_Tarjeta { get; set; }
        public decimal IdCliente { get; set; }
        public string NomCliente { get; set; }
        public double Valor_Aplicado { get; set; }
        public string Referencia { get; set; }
        public string IdCobro_tipo { get; set; }
    }
}
