//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFa_TipoNota_x_Empresa
    {
        public int IdEmpresa { get; set; }
        public int IdTipoNota { get; set; }
        public string CodTipoNota { get; set; }
        public string Tipo { get; set; }
        public string No_Descripcion { get; set; }
        public string Nemonico { get; set; }
        public string InternoSis { get; set; }
        public string SeDeclaraSRI { get; set; }
        public string IdCtaCble { get; set; }
        public string Estado { get; set; }
    }
}
