//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_movimientos_x_bodega_x_cat
    {
        public Nullable<System.DateTime> cm_fecha { get; set; }
        public string cm_observacion { get; set; }
        public string TipoMoviInvent { get; set; }
        public string ca_Categoria { get; set; }
        public string IdCategoria { get; set; }
        public string Descripcion { get; set; }
        public string pr_descripcion { get; set; }
        public string bo_Descripcion { get; set; }
        public string pr_codigo { get; set; }
        public string Su_Descripcion { get; set; }
        public double dm_cantidad { get; set; }
        public decimal IdProducto { get; set; }
        public decimal IdNumMovi { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public int IdBodega { get; set; }
        public int IdSucursal { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public string pe_nombreCompleto { get; set; }
        public decimal IdCbteVta { get; set; }
        public string vt_NumFactura { get; set; }
        public string vt_Observacion { get; set; }
        public string CodGuiaRemision { get; set; }
        public string NumGuia_Preimpresa { get; set; }
        public string NUAutorizacion { get; set; }
        public string Estado { get; set; }
    }
}
