//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFa_Formas_Pago_x_Factura_DeclaracionSRI
    {
        public int IdEmpresa { get; set; }
        public string IdTipoDocumento { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string vt_tipoDoc { get; set; }
        public Nullable<int> Idanio { get; set; }
        public Nullable<int> IdMes { get; set; }
        public string IdFormaPago { get; set; }
    }
}
