//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_ContabilizarNotaCredDeb_x_Item
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdNota { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Sub_total { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Des_total { get; set; }
        public Nullable<int> IdPunto_cargo_grupo { get; set; }
        public Nullable<int> IdPunto_Cargo { get; set; }
        public decimal IdProducto { get; set; }
        public string IdCtaCble_Vta { get; set; }
        public string IdCtaCble_Des0 { get; set; }
        public string IdCtaCble_DesIva { get; set; }
        public string IdCod_Impuesto_Iva { get; set; }
        public string IdCod_Impuesto_Ice { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public string IdCtaCble_Iva { get; set; }
        public string IdCtaCble_Ice { get; set; }
    }
}
