//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_pedido_x_fa_orden_Desp_det_x_fa_guia_remision_det
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdPedido { get; set; }
        public decimal IdProducto { get; set; }
        public double dp_cantidad { get; set; }
        public double gi_cantidad_guia { get; set; }
        public double saldo_cantidad_pedido { get; set; }
    }
}
