//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_grupo_x_sub_centro_costo_det
    {
        public int IdEmpresa { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public string cod_subcentroCosto { get; set; }
        public string Centro_costo { get; set; }
        public string pc_Estado { get; set; }
        public string IdCtaCble { get; set; }
        public decimal IdGrupo { get; set; }
    }
}
