//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_liquidacion_x_punto_cargo_det_ing_egr_inven
    {
        public long IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public int Secuencia { get; set; }
        public string IdUnidadMedida { get; set; }
        public string nom_uni_medida { get; set; }
        public decimal IdProducto { get; set; }
        public string pr_descripcion { get; set; }
        public string cod_orden_mantenimiento { get; set; }
        public string Genera_Movi_Inven { get; set; }
        public double dm_cantidad { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public double mv_costo { get; set; }
        public string signo { get; set; }
        public Nullable<int> li_IdEmpresa { get; set; }
        public Nullable<int> li_IdSucursal { get; set; }
        public string li_IdCentroCosto { get; set; }
        public Nullable<decimal> li_IdLiquidacion { get; set; }
    }
}
