//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_conciliacion_horas_maquina_vs_horas_hombre
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdActivoFijo { get; set; }
        public int IdTipoDepreciacion { get; set; }
        public string CodActivoFijo { get; set; }
        public string Af_Nombre { get; set; }
        public Nullable<double> Af_ValorUnidad_Actu { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> Horas_Trabajada_x_Af { get; set; }
        public int IdPeriodo { get; set; }
        public string pe_nombreCompleto { get; set; }
        public Nullable<double> hora_trabajada { get; set; }
    }
}
