//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_registro_unidades_x_equipo_para_facturacion
    {
        public long IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdRegistro { get; set; }
        public int IdActivoFijo { get; set; }
        public Nullable<double> Af_ValorUnidad_Actu { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<int> IdEmpresa_hn { get; set; }
        public Nullable<int> IdSucursal_hn { get; set; }
        public Nullable<int> IdBodega_hn { get; set; }
        public Nullable<decimal> IdCbteVta_hn { get; set; }
        public double unidades_maximas { get; set; }
        public double diferencia_a_facturar { get; set; }
        public int IdPunto_cargo { get; set; }
        public string nom_punto_cargo { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public Nullable<int> IdPunto_cargo_grupo { get; set; }
        public Nullable<int> IdEmpresa_he { get; set; }
        public Nullable<int> IdSucursal_he { get; set; }
        public Nullable<int> IdBodega_he { get; set; }
        public Nullable<decimal> IdCbteVta_he { get; set; }
    }
}
