//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFa_Pedido_det_x_orden_desp_conSaldo
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdPedido { get; set; }
        public int Secuencial { get; set; }
        public decimal IdProducto { get; set; }
        public Nullable<double> dp_cantidad { get; set; }
        public Nullable<double> od_cantidad { get; set; }
        public Nullable<double> pd_saldo { get; set; }
        public string detelleSys { get; set; }
    }
}
