//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_pre_facturacion_det_Poliza_x_AF_det_cuota
    {
        public int IdEmpresa { get; set; }
        public decimal IdPoliza { get; set; }
        public string cod_couta { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public double valor_prima { get; set; }
        public string IdEstadoFacturacion_cat { get; set; }
    }
}
