//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Movi_Inven_CusCider_Cab
    {
        public int IdEmpresa { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public int IdBodega { get; set; }
        public int IdSucursal { get; set; }
        public string CodMoviInven { get; set; }
        public string cm_tipo { get; set; }
        public string cm_observacion { get; set; }
        public System.DateTime cm_fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public Nullable<decimal> IdProvedor { get; set; }
        public decimal IdNumMovi { get; set; }
        public string Su_Descripcion { get; set; }
        public string bo_Descripcion { get; set; }
        public string Codigo { get; set; }
        public string tm_descripcion { get; set; }
        public string pr_nombre { get; set; }
    }
}
