//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_movi_inve_fecha_costeo_recomendada_x_sucursal
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public Nullable<System.DateTime> fecha_sin_costear { get; set; }
        public bool Costeado { get; set; }
    }
}
