//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_MoviemientoInvetarioXImportacion
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int in_IdBodega { get; set; }
        public decimal IdOrdenCompraExt { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public decimal Expr1 { get; set; }
        public Nullable<double> dm_cantidad_Ingresa { get; set; }
        public Nullable<double> di_cantidad_Solicitada { get; set; }
        public Nullable<double> SaldoxIngresar { get; set; }
    }
}
