//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Producto_a_Cortar_CusCider
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdProducto { get; set; }
        public string pr_codigo { get; set; }
        public string pr_codigo_barra { get; set; }
        public int IdProductoTipo { get; set; }
        public string IdPresentacion { get; set; }
        public string IdCategoria { get; set; }
        public string pr_descripcion { get; set; }
        public string pr_observacion { get; set; }
        public string IdUnidadMedida { get; set; }
        public double pr_precio_publico { get; set; }
        public int IdMarca { get; set; }
        public double pr_stock_minimo { get; set; }
        public int IdSubGrupo { get; set; }
        public int IdGrupo { get; set; }
        public int IdLinea { get; set; }
        public string pr_descripcion_2 { get; set; }
        public string Estado { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public int mv_Secuencia { get; set; }
        public int Secuencia { get; set; }
        public string CodigoBarra { get; set; }
        public string mv_tipo_movi { get; set; }
        public double dm_cantidad { get; set; }
        public string dm_observacion { get; set; }
        public double dm_precio { get; set; }
        public double mv_costo { get; set; }
        public string ca_Categoria { get; set; }
        public string Su_Descripcion { get; set; }
        public string bo_Descripcion { get; set; }
        public string tp_descripcion { get; set; }
        public string Descripcion { get; set; }
        public string ot_CodObra { get; set; }
        public Nullable<int> et_IdProcesoProductivo { get; set; }
        public Nullable<decimal> ot_IdOrdenTaller { get; set; }
        public string IdUnidadMedida_Consumo { get; set; }
    }
}
