//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_ReimpresionCodigoBarraProductoTerminado_CusCider
    {
        public int IdEmpresa { get; set; }
        public decimal IdEnsamblado { get; set; }
        public int IdSucursal { get; set; }
        public string CodigoBarra { get; set; }
        public string Obra { get; set; }
        public string OrdenTaller { get; set; }
        public string Cliente { get; set; }
        public decimal IdProducto { get; set; }
        public string pr_descripcion { get; set; }
        public byte[] em_logo { get; set; }
        public string CodObra { get; set; }
    }
}
