//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Producto_x_Proveedor
    {
        public int IdEmpresa_prod { get; set; }
        public int IdEmpresa_prov { get; set; }
        public decimal IdProducto { get; set; }
        public decimal IdProveedor { get; set; }
        public string pr_descripcion { get; set; }
        public string pr_nombre { get; set; }
    }
}
