//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_Despacho
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string CodObra { get; set; }
        public decimal IdDespacho { get; set; }
        public decimal IdCliente { get; set; }
        public string NumDespacho { get; set; }
        public int IdBodega { get; set; }
        public string bo_Descripcion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string PuntoPartida { get; set; }
        public string PuntoLLegada { get; set; }
        public string Chofer { get; set; }
        public string Placa { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string NumGuiaRemision { get; set; }
        public System.DateTime FechaIniTras { get; set; }
        public System.DateTime FechaFinTras { get; set; }
        public string TipoTransporte { get; set; }
        public string NumFactura { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string Su_Descripcion { get; set; }
        public string ob_descripcion { get; set; }
        public string ruta { get; set; }
    }
}
