//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_MovPteGrua
    {
        public string ob_descripcion { get; set; }
        public string pp_descripcion { get; set; }
        public string EtapaOrigen { get; set; }
        public string EtapaDestino { get; set; }
        public int etOriPosicion { get; set; }
        public int etDestPosicion { get; set; }
        public double EtDestPorc { get; set; }
        public double EtOriPorc { get; set; }
        public decimal IdProducto { get; set; }
        public decimal CantidadPieza { get; set; }
        public decimal TotalPeso { get; set; }
        public string ot_desc { get; set; }
        public string pr_descripcion { get; set; }
        public string CodObra { get; set; }
    }
}
