//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_OrdenTaller
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdOrdenTaller { get; set; }
        public string CodObra { get; set; }
        public int NumeroOT { get; set; }
        public decimal IdProducto { get; set; }
        public decimal CantidadPieza { get; set; }
        public decimal TotalPeso { get; set; }
        public string Estado { get; set; }
        public string Su_Descripcion { get; set; }
        public string Observacion { get; set; }
        public string Codigo { get; set; }
        public decimal PesoUnitaro { get; set; }
        public System.DateTime ot_FechaReg { get; set; }
        public string pr_descripcion { get; set; }
        public string ob_descripcion { get; set; }
        public string ca_Categoria { get; set; }
        public decimal IdCliente { get; set; }
        public Nullable<decimal> IdListadoDiseno { get; set; }
        public Nullable<double> longitudProducto { get; set; }
        public Nullable<decimal> LongitudUnitaria { get; set; }
        public Nullable<decimal> TotalLongitud { get; set; }
        public string lm_Observacion { get; set; }
    }
}
