//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_Ensamblado_CusCidersus
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdEnsamblado { get; set; }
        public int IdBodega { get; set; }
        public decimal IdGrupoTrabajo { get; set; }
        public decimal IdProducto { get; set; }
        public string CodigoBarra { get; set; }
        public string CodObra { get; set; }
        public decimal IdOrdenTaller { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuarioAnu { get; set; }
        public string MotivoAnu { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> FechaAnu { get; set; }
        public System.DateTime FechaTransac { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public int IdProcesoProductivo { get; set; }
        public int IdEtapa { get; set; }
        public string Codigo { get; set; }
        public string ob_descripcion { get; set; }
        public string bo_Descripcion { get; set; }
        public string gt_descripcion { get; set; }
        public string pr_descripcion { get; set; }
        public string Su_Descripcion { get; set; }
    }
}
