//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_ProcesoProductivo
    {
        public string pp_Estado { get; set; }
        public int IdEmpresa_Pr { get; set; }
        public int IdProcesoProductivo { get; set; }
        public string CodObra { get; set; }
        public string ob_descripcion { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string ob_Estado { get; set; }
    }
}
