//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_GrupoTrabajo_x_Etapa
    {
        public string NombreEtapa { get; set; }
        public string gt_descripcion { get; set; }
        public decimal IdGrupoTrabajo { get; set; }
        public int IdSucursal { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdLider { get; set; }
        public int IdEtapa { get; set; }
        public string CodObra { get; set; }
    }
}
