//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_Saldos_x_Req_x_OT_x_Consumo
    {
        public decimal IdTransaccion { get; set; }
        public int IdDetTrans { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string Codigo { get; set; }
        public int ped_IdEmp { get; set; }
        public int ped_IdSuc { get; set; }
        public string ped_codobra { get; set; }
        public decimal ped_IdOT { get; set; }
        public decimal ped_IdProducto { get; set; }
        public Nullable<decimal> IdListadoMateriales { get; set; }
        public Nullable<int> IdDetalle { get; set; }
        public Nullable<int> oc_IdEmpresa { get; set; }
        public Nullable<decimal> oc_IdOrdenCompra { get; set; }
        public string IdEstadoAprob { get; set; }
        public string oc_NumDocumento { get; set; }
        public string EstadoRecepcion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdMovi_inven_tipo { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<decimal> IdNumMovi { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public string mv_tipo_movi { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public Nullable<int> ot_IdEmpresa { get; set; }
        public Nullable<int> ot_IdSucursal { get; set; }
        public string ot_CodObra { get; set; }
        public Nullable<decimal> ot_IdOrdenTaller { get; set; }
        public Nullable<double> saldo { get; set; }
        public double ped_saldo { get; set; }
        public Nullable<double> ent_saldo { get; set; }
    }
}
