//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_turno_x_tb_dia
    {
        public int IdEmpresa { get; set; }
        public decimal IdTurno { get; set; }
        public byte idDia { get; set; }
        public bool Activo { get; set; }
        public string sdia { get; set; }
        public string nemonico { get; set; }
        public string sdiaIngles { get; set; }
    }
}
