//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_NominaTipoLiquiOrdenXRubro
    {
        public int IdEmpresa { get; set; }
        public int IdNominaTipo { get; set; }
        public int IdNominaTipoLiqui { get; set; }
        public int Orden { get; set; }
        public string IdRubro { get; set; }
        public string Formula { get; set; }
        public Nullable<bool> EsVisible { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaIngresa { get; set; }
        public string UsuarioIngresa { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string UsuarioModifica { get; set; }
        public string ru_codRolGen { get; set; }
        public string ru_descripcion { get; set; }
        public string ru_tipo { get; set; }
        public string ru_estado { get; set; }
        public Nullable<bool> rub_concep { get; set; }
        public Nullable<int> rub_tipcal { get; set; }
        public string rub_formul { get; set; }
        public Nullable<decimal> rub_valfij { get; set; }
        public Nullable<bool> rub_guarda_rol { get; set; }
    }
}
