//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_ro_empleado_x_Activo_Fijo
    {
        public int IdEmpresa { get; set; }
        public int IdActivo_fijo { get; set; }
        public decimal IdEmpleado { get; set; }
        public System.DateTime Fecha_Asignacion { get; set; }
        public System.DateTime Fecha_Hasta { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string de_descripcion { get; set; }
        public string Descripcion { get; set; }
        public string Af_Nombre { get; set; }
        public string Af_DescripcionCorta { get; set; }
        public Nullable<int> IdNomina_tipo { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
    }
}
