//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_FormaPago_Prestamo
    {
        public string CodCatalogo { get; set; }
        public int IdCatalogo { get; set; }
        public string ca_descripcion { get; set; }
        public int IdTipoCatalogo { get; set; }
        public int ca_orden { get; set; }
        public string ca_estado { get; set; }
    }
}
