//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_Config_Rubros_x_Empresa_AportaIess
    {
        public int IdEmpresa { get; set; }
        public string IdRubro { get; set; }
        public string ru_descripcion { get; set; }
        public string NombreCorto { get; set; }
        public string rub_codigo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> Fecha_Transac { get; set; }
        public Nullable<int> IdUsuarioUltMod { get; set; }
        public Nullable<int> Fecha_UltMod { get; set; }
        public Nullable<int> IdUsuarioUltAnu { get; set; }
        public Nullable<int> Fecha_UltAnu { get; set; }
        public Nullable<int> nom_pc { get; set; }
        public Nullable<int> ip { get; set; }
    }
}
