//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Config_rubros_x_Prestamo
    {
        public int IdEmpresa { get; set; }
        public Nullable<int> orden_prest { get; set; }
        public string IdRubro_prest { get; set; }
        public string rub_codigo_prest { get; set; }
        public string ru_descripcion_prest { get; set; }
        public string NombreCorto_prest { get; set; }
        public string ru_tipo_prest { get; set; }
        public string ru_estado_prest { get; set; }
    }
}
