//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_Ing_Egre_x_Empleado
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public int IdPeriodo { get; set; }
        public string IdRubro { get; set; }
        public decimal IdNovedad { get; set; }
        public int SecuenciaNovedad { get; set; }
        public decimal IdPrestamo { get; set; }
        public decimal NunCouta { get; set; }
        public string IngEgr { get; set; }
        public double Valor { get; set; }
        public int iAnio { get; set; }
        public int iMes { get; set; }
        public string cerrado { get; set; }
        public string observacionesSys { get; set; }
        public string TipoRegistro { get; set; }
        public Nullable<int> IdDivision { get; set; }
        public string Descripcion { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string rub_codigo { get; set; }
        public double em_sueldoBasicoMen { get; set; }
        public string ru_descripcion { get; set; }
        public string de_descripcion { get; set; }
        public int IdDepartamento { get; set; }
    }
}
