//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_fectividad_Entrega_servicio
    {
        public int IdEmpresa { get; set; }
        public decimal IdNivelServicio { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_tipo_Liq { get; set; }
        public int IdPeriodo { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
        public string IdUsuario { get; set; }
        public string DescripcionProcesoNomina { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> pe_FechaIni { get; set; }
        public Nullable<System.DateTime> pe_FechaFin { get; set; }
        public int IdServicioTipo { get; set; }
    }
}
