//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Conf_Rubros_Acumulados_x_Empresa
    {
        public int IdEmpresa { get; set; }
        public string IdRubro { get; set; }
        public string ru_descripcion { get; set; }
        public Nullable<bool> Configurable { get; set; }
    }
}
