//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Area_x_Division
    {
        public int IdEmpresa { get; set; }
        public int IdDivision { get; set; }
        public int IdArea { get; set; }
        public string Descripcion { get; set; }
        public string estado { get; set; }
        public string Descripcion_Division { get; set; }
        public string MotiAnula { get; set; }
    }
}
