//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_fectividad_Entrega_servicio
    {
        public int IdEmpresa { get; set; }
        public decimal IdNivelServicio { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_tipo_Liq { get; set; }
        public int IdPeriodo { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
        public string IdUsuario { get; set; }
        public string DescripcionProcesoNomina { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> pe_FechaIni { get; set; }
        public Nullable<System.DateTime> pe_FechaFin { get; set; }
        public int IdServicioTipo { get; set; }
    }
}
