//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Novedades_Batch
    {
        public int IdEmpresa { get; set; }
        public string IdCalendario { get; set; }
        public string IdRubro { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public string ru_descripcion { get; set; }
        public string NombreCorto { get; set; }
        public int IdCarga { get; set; }
    }
}
