//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_ConfLiqui_X_Empleado
    {
        public Nullable<int> IdEmpresa { get; set; }
        public string IdRubro { get; set; }
        public string Descripción { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> SecuPresentacion { get; set; }
    }
}
