//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Total_IngEgr_x_Empleado
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<double> totIng { get; set; }
        public Nullable<double> totEgr { get; set; }
        public Nullable<double> totNeto { get; set; }
        public string NomCompleto { get; set; }
        public string cargo { get; set; }
        public string departamento { get; set; }
        public string em_codigo { get; set; }
        public string pe_cedulaRuc { get; set; }
    }
}
