//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Rubro_x_Empleado_x_nomina_x_TipoLiqui
    {
        public int IdEmpresa { get; set; }
        public int IdNomina_Tipo { get; set; }
        public string Descripcion { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public string DescripcionProcesoNomina { get; set; }
        public string IdRubro { get; set; }
        public string rub_codigo { get; set; }
        public string ru_descripcion { get; set; }
    }
}
