//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_empleado_por_novedades
    {
        public int IdEmpresa { get; set; }
        public decimal IdTransaccion { get; set; }
        public decimal IdEmpleado { get; set; }
        public string NombreCompleto { get; set; }
        public string IdRubro { get; set; }
        public string DescripcionRubro { get; set; }
        public int TipoNomina { get; set; }
        public string DescripcionNomina { get; set; }
        public int TipoLiquidacion { get; set; }
        public string DescripcionProceso { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
    }
}
