//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Rol_DetalleXEmpleado
    {
        public string pe_cedulaRuc { get; set; }
        public string NombreCompleto { get; set; }
        public string Cargo { get; set; }
        public string Departamento { get; set; }
        public int IdNominaTipo { get; set; }
        public int IdNominaTipoLiqui { get; set; }
        public int IdPeriodo { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdPersona { get; set; }
        public string em_estado { get; set; }
        public string IdRubro { get; set; }
        public string ru_tipo { get; set; }
        public string ru_descripcion { get; set; }
        public double Valor { get; set; }
        public decimal IdEmpleado { get; set; }
        public int Orden { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> rub_visible_reporte { get; set; }
    }
}
