//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_tb_banco_procesos_bancarios
    {
        public int IdEmpresa { get; set; }
        public string IdProceso_bancario_tipo { get; set; }
        public int IdBanco { get; set; }
        public string cod_banco { get; set; }
        public string Codigo_Empresa { get; set; }
        public string Iniciales_Archivo { get; set; }
        public string nom_proceso_bancario { get; set; }
        public Nullable<decimal> Secuencial_detalle_inicial { get; set; }
        public Nullable<int> IdTipoNota { get; set; }
        public Nullable<bool> Se_contabiliza { get; set; }
        public string Tipo_Proc { get; set; }
    }
}
