//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_Bodega_x_Sucursal_TreeList
    {
        public int IdEmpresa { get; set; }
        public string Id { get; set; }
        public string IdPadre { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public int Nivel { get; set; }
        public int IdSucursal { get; set; }
        public Nullable<int> IdBodega { get; set; }
    }
}
