//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_matricula_Tipo_documento
    {
        public Aca_matricula_Tipo_documento()
        {
            this.Aca_matricula_x_documento = new HashSet<Aca_matricula_x_documento>();
        }
    
        public int IdTipoDocumento { get; set; }
        public string codTipoDocumento { get; set; }
        public string descripcion { get; set; }
        public byte[] Archivo { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual ICollection<Aca_matricula_x_documento> Aca_matricula_x_documento { get; set; }
    }
}
