//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_curso_x_Aca_Rubro
    {
        public int IdCurso { get; set; }
        public int IdRubro { get; set; }
        public string observacion { get; set; }
        public bool estado { get; set; }
    }
}
