//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Pre_Facturacion
    {
        public Aca_Pre_Facturacion()
        {
            this.Aca_Pre_Facturacion_det = new HashSet<Aca_Pre_Facturacion_det>();
        }
    
        public int IdInstitucion { get; set; }
        public decimal IdPreFacturacion { get; set; }
        public int IdInstitucion_contrato { get; set; }
        public int IdPeriodo { get; set; }
        public System.DateTime fecha_prefacturacion { get; set; }
        public int IdEmpresa_fact { get; set; }
        public int IdSucursal_fact { get; set; }
        public Nullable<int> IdBodega_fact { get; set; }
        public Nullable<decimal> IdCbteVta { get; set; }
        public int IdPtoVta_fact { get; set; }
        public int IdCaja_fact { get; set; }
        public int IdGrupoFE { get; set; }
        public System.DateTime vt_fecha_fact { get; set; }
        public int vt_plazo_fact { get; set; }
        public System.DateTime vt_fech_venc { get; set; }
        public string observacion_fact { get; set; }
        public string Estado_Pre_factutacion_Cat { get; set; }
    
        public virtual Aca_Rubro_Grupo_FE Aca_Rubro_Grupo_FE { get; set; }
        public virtual ICollection<Aca_Pre_Facturacion_det> Aca_Pre_Facturacion_det { get; set; }
    }
}
