//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_curso
    {
        public Aca_curso()
        {
            this.Aca_Admision = new HashSet<Aca_Admision>();
            this.Aca_Paralelo = new HashSet<Aca_Paralelo>();
        }
    
        public int IdCurso { get; set; }
        public int IdSeccion { get; set; }
        public string CodCurso { get; set; }
        public string CodAlternoCur { get; set; }
        public string Descripcion_cur { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public bool es_sistema_dual { get; set; }
    
        public virtual Aca_Seccion Aca_Seccion { get; set; }
        public virtual ICollection<Aca_Admision> Aca_Admision { get; set; }
        public virtual ICollection<Aca_Paralelo> Aca_Paralelo { get; set; }
    }
}
