//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Documento_Bancario_x_Rep_Economico_x_estudiante_x_Matricula
    {
        public int IdInstitucion { get; set; }
        public decimal IdFamiliar { get; set; }
        public string IdParentesco_cat { get; set; }
        public int IdDocumento_Bancario { get; set; }
        public decimal IdEstudiante { get; set; }
        public decimal IdMatricula { get; set; }
        public int Id_tipo_meca_pago { get; set; }
        public int Id_tb_banco_x_mgbanco { get; set; }
        public string Observacion { get; set; }
    
        public virtual tb_banco_x_mg_banco tb_banco_x_mg_banco { get; set; }
        public virtual Aca_Documento_Bancario_x_Rep_Economico Aca_Documento_Bancario_x_Rep_Economico { get; set; }
        public virtual Aca_estudiante Aca_estudiante { get; set; }
        public virtual Aca_Tipo_Mecanismo_Pago Aca_Tipo_Mecanismo_Pago { get; set; }
    }
}
