//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Rubro_Grupo_FE
    {
        public Aca_Rubro_Grupo_FE()
        {
            this.Aca_Pre_Facturacion = new HashSet<Aca_Pre_Facturacion>();
            this.Aca_tb_bancos_procesos_bancarios_x_empresa_x_Grupo_FE = new HashSet<Aca_tb_bancos_procesos_bancarios_x_empresa_x_Grupo_FE>();
        }
    
        public int IdInstitucion { get; set; }
        public int IdGrupoFE { get; set; }
        public string CodGrupoFE { get; set; }
        public string nom_GrupoFe { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual ICollection<Aca_Pre_Facturacion> Aca_Pre_Facturacion { get; set; }
        public virtual ICollection<Aca_tb_bancos_procesos_bancarios_x_empresa_x_Grupo_FE> Aca_tb_bancos_procesos_bancarios_x_empresa_x_Grupo_FE { get; set; }
    }
}
