//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_notaCredDeb_aca
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdNotaCredDeb { get; set; }
        public Nullable<int> IdInstitucion { get; set; }
        public decimal IdEstudiante { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Aca_estudiante Aca_estudiante { get; set; }
    }
}
