//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Aca_Rubro_x_Periodo_x_Rubro_x_Fa_Descuento
    {
        public int IdInstitucion_per { get; set; }
        public int IdAnioLectivo { get; set; }
        public int IdInstitucion_rub { get; set; }
        public int IdPeriodo { get; set; }
        public int IdRubro { get; set; }
        public double ValorRubro { get; set; }
        public Nullable<double> Valor_Descuento { get; set; }
        public Nullable<int> IdEmpresa_fadesc { get; set; }
        public Nullable<decimal> IdDescuento { get; set; }
        public Nullable<double> de_porcentaje { get; set; }
        public Nullable<bool> estado_rubro_x_fa_descuento { get; set; }
        public int tiene_descuento { get; set; }
    }
}
