//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAca_Contrato_x_Estudiante_Det_x_Rubro_x_fa_descuento
    {
        public Nullable<long> id { get; set; }
        public int IdInstitucion { get; set; }
        public decimal IdContrato { get; set; }
        public decimal IdRubro { get; set; }
        public double ValorRubro { get; set; }
        public Nullable<double> Valor_Descuento { get; set; }
        public int IdInstitucion_Per { get; set; }
        public int IdAnioLectivo_Per { get; set; }
        public int IdPeriodo_Per { get; set; }
        public Nullable<int> IdEmpresa_fadesc { get; set; }
        public Nullable<decimal> IdDescuento { get; set; }
        public Nullable<double> de_porcentaje { get; set; }
        public Nullable<System.DateTime> FechaCreacionContDet { get; set; }
        public Nullable<bool> estado_rubro_x_fa_descuento { get; set; }
        public int tiene_descuento { get; set; }
    }
}
