//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAca_Familiar_x_Estudiante_Padre
    {
        public decimal IdEstudiante { get; set; }
        public decimal IdFamiliar { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string IdParentesco_cat { get; set; }
        public decimal IdPersona { get; set; }
        public string Titulo { get; set; }
        public string empresa_telefono { get; set; }
        public string empresa_donde_trabaja { get; set; }
        public string empresa_direccion { get; set; }
        public string IdNivelEducativo_cat { get; set; }
        public int IdInstitucion { get; set; }
    }
}
