//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAca_matricula_documento
    {
        public int IdInstitucion { get; set; }
        public int IdSede { get; set; }
        public decimal IdMatricula { get; set; }
        public int IdTipoDocumento { get; set; }
        public string descripcion { get; set; }
        public byte[] Archivo { get; set; }
        public Nullable<bool> Existe_en_Base { get; set; }
        public string Estado { get; set; }
    }
}
