//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAca_Pre_Facturacion_det_Generar_Archivo_Banco
    {
        public Nullable<long> id { get; set; }
        public int IdInstitucion { get; set; }
        public decimal IdPreFacturacion { get; set; }
        public int Secuencia_Proce { get; set; }
        public int secuencia { get; set; }
        public int IdRubro { get; set; }
        public int IdInstitucion_contra { get; set; }
        public decimal IdContrato { get; set; }
        public int IdInstitucion_Per { get; set; }
        public int IdPeriodo_Per { get; set; }
        public int IdGrupoFE { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public double vt_cantidad { get; set; }
        public double vt_Precio { get; set; }
        public double vt_PorDescUnitario { get; set; }
        public double vt_DescUnitario { get; set; }
        public double vt_PrecioFinal { get; set; }
        public double vt_Subtotal { get; set; }
        public double vt_iva_valor { get; set; }
        public double vt_total { get; set; }
        public string IdCod_Impuesto_Iva { get; set; }
        public string observacion_det { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_nombre { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string Descripcion_paralelo { get; set; }
        public string Descripcion_cur { get; set; }
        public string Descripcion_secc { get; set; }
        public string Descripcion_Jor { get; set; }
        public string Numero_Documento { get; set; }
        public int IdTipoPersona { get; set; }
        public string IdTipoDocumento { get; set; }
        public string Tipo_documento_cat { get; set; }
        public bool activo { get; set; }
        public decimal IdEstudiante { get; set; }
        public int IdCurso { get; set; }
        public int IdParalelo { get; set; }
        public int IdSeccion { get; set; }
        public int IdJornada { get; set; }
        public int IdSede { get; set; }
        public string Descripcion_sede { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public int IdDocumento_Bancario { get; set; }
        public int IdAnioLectivo_Per { get; set; }
        public int Id_tipo_meca_pago { get; set; }
        public int Id_tb_banco_x_mgbanco { get; set; }
        public string idProceso_Bancario_Tipo { get; set; }
        public string codigo_unico_estudiante { get; set; }
        public decimal IdFamiliar { get; set; }
        public string IdParentesco_cat { get; set; }
        public Nullable<double> ValorPagado { get; set; }
        public double saldos { get; set; }
        public int esta_en_archivo { get; set; }
        public string concepto_estado_cuenta { get; set; }
        public Nullable<bool> estado_contrato_pago_garantizado { get; set; }
        public string codigo_empresa_proceso_bancario { get; set; }
        public Nullable<System.DateTime> Fecha_Expiracion { get; set; }
    }
}
