//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAca_Contrato_x_Estudiante_det_Excepciones
    {
        public int IdInstitucion { get; set; }
        public int IdAnioLectivo { get; set; }
        public Nullable<int> IdSede { get; set; }
        public Nullable<int> IdJornada { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<int> IdCurso { get; set; }
        public Nullable<int> IdParalelo { get; set; }
        public Nullable<decimal> IdMatricula { get; set; }
        public decimal IdContrato { get; set; }
        public decimal IdEstudiante { get; set; }
        public decimal IdRubro { get; set; }
        public int IdInstitucion_Per { get; set; }
        public int IdAnioLectivo_Per { get; set; }
        public int IdPeriodo_Per { get; set; }
        public string sede { get; set; }
        public string jornada { get; set; }
        public string seccion { get; set; }
        public string curso { get; set; }
        public string paralelo { get; set; }
        public string cedula_Estudiante { get; set; }
        public string nombre_Estudiante { get; set; }
        public string nombreCompleto_Estudiante { get; set; }
        public string apellido_Estudiante { get; set; }
        public string Descripcion_rubro { get; set; }
        public double Valor { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime pe_FechaIni { get; set; }
        public System.DateTime pe_FechaFin { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<decimal> IdDescuento { get; set; }
        public string descuento { get; set; }
        public string nom_descuento { get; set; }
        public int TieneDescuento { get; set; }
        public Nullable<double> ValorExepcion { get; set; }
        public Nullable<double> porcentaje_excepcion { get; set; }
        public Nullable<decimal> IdExepcion { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
